using Ntms.Domain.Entities;

namespace Ntms.Infrastructure.Persistence;

/// <summary>
/// State and district master from the Local Government Directory (LGD),
/// Ministry of Panchayati Raj - the Government of India standard location
/// directory. LGD codes are used as the primary keys, so the values stored
/// here line up with every other government system.
///
/// Source: https://lgdirectory.gov.in/
/// 36 states and union territories, 763 districts.
/// </summary>
public static class LgdSeedData
{
    public static IReadOnlyList<LgdState> States { get; } =
    [
        new() { Code = 35, Name = "ANDAMAN AND NICOBAR ISLANDS", IsUnionTerritory = true },
        new() { Code = 28, Name = "ANDHRA PRADESH", IsUnionTerritory = false },
        new() { Code = 12, Name = "ARUNACHAL PRADESH", IsUnionTerritory = false },
        new() { Code = 18, Name = "ASSAM", IsUnionTerritory = false },
        new() { Code = 10, Name = "BIHAR", IsUnionTerritory = false },
        new() { Code = 4, Name = "CHANDIGARH", IsUnionTerritory = true },
        new() { Code = 22, Name = "CHHATTISGARH", IsUnionTerritory = false },
        new() { Code = 7, Name = "DELHI", IsUnionTerritory = true },
        new() { Code = 30, Name = "GOA", IsUnionTerritory = false },
        new() { Code = 24, Name = "GUJARAT", IsUnionTerritory = false },
        new() { Code = 6, Name = "HARYANA", IsUnionTerritory = false },
        new() { Code = 2, Name = "HIMACHAL PRADESH", IsUnionTerritory = false },
        new() { Code = 1, Name = "JAMMU AND KASHMIR", IsUnionTerritory = true },
        new() { Code = 20, Name = "JHARKHAND", IsUnionTerritory = false },
        new() { Code = 29, Name = "KARNATAKA", IsUnionTerritory = false },
        new() { Code = 32, Name = "KERALA", IsUnionTerritory = false },
        new() { Code = 37, Name = "LADAKH", IsUnionTerritory = true },
        new() { Code = 31, Name = "LAKSHADWEEP", IsUnionTerritory = true },
        new() { Code = 23, Name = "MADHYA PRADESH", IsUnionTerritory = false },
        new() { Code = 27, Name = "MAHARASHTRA", IsUnionTerritory = false },
        new() { Code = 14, Name = "MANIPUR", IsUnionTerritory = false },
        new() { Code = 17, Name = "MEGHALAYA", IsUnionTerritory = false },
        new() { Code = 15, Name = "MIZORAM", IsUnionTerritory = false },
        new() { Code = 13, Name = "NAGALAND", IsUnionTerritory = false },
        new() { Code = 21, Name = "ODISHA", IsUnionTerritory = false },
        new() { Code = 34, Name = "PUDUCHERRY", IsUnionTerritory = true },
        new() { Code = 3, Name = "PUNJAB", IsUnionTerritory = false },
        new() { Code = 8, Name = "RAJASTHAN", IsUnionTerritory = false },
        new() { Code = 11, Name = "SIKKIM", IsUnionTerritory = false },
        new() { Code = 33, Name = "TAMIL NADU", IsUnionTerritory = false },
        new() { Code = 36, Name = "TELANGANA", IsUnionTerritory = false },
        new() { Code = 38, Name = "THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU", IsUnionTerritory = true },
        new() { Code = 16, Name = "TRIPURA", IsUnionTerritory = false },
        new() { Code = 9, Name = "UTTAR PRADESH", IsUnionTerritory = false },
        new() { Code = 5, Name = "UTTARAKHAND", IsUnionTerritory = false },
        new() { Code = 19, Name = "WEST BENGAL", IsUnionTerritory = false },
    ];

    public static IReadOnlyList<LgdDistrict> Districts { get; } =
    [
        new() { Code = 1, StateCode = 1, Name = "ANANTNAG" },
        new() { Code = 623, StateCode = 1, Name = "BANDIPORA" },
        new() { Code = 3, StateCode = 1, Name = "BARAMULLA" },
        new() { Code = 2, StateCode = 1, Name = "Budgam" },
        new() { Code = 4, StateCode = 1, Name = "DODA" },
        new() { Code = 626, StateCode = 1, Name = "GANDERBAL" },
        new() { Code = 5, StateCode = 1, Name = "JAMMU" },
        new() { Code = 7, StateCode = 1, Name = "KATHUA" },
        new() { Code = 620, StateCode = 1, Name = "KISHTWAR" },
        new() { Code = 622, StateCode = 1, Name = "KULGAM" },
        new() { Code = 8, StateCode = 1, Name = "KUPWARA" },
        new() { Code = 10, StateCode = 1, Name = "POONCH" },
        new() { Code = 11, StateCode = 1, Name = "PULWAMA" },
        new() { Code = 12, StateCode = 1, Name = "RAJOURI" },
        new() { Code = 621, StateCode = 1, Name = "RAMBAN" },
        new() { Code = 627, StateCode = 1, Name = "REASI" },
        new() { Code = 624, StateCode = 1, Name = "SAMBA" },
        new() { Code = 625, StateCode = 1, Name = "SHOPIAN" },
        new() { Code = 13, StateCode = 1, Name = "SRINAGAR" },
        new() { Code = 14, StateCode = 1, Name = "UDHAMPUR" },
        new() { Code = 15, StateCode = 2, Name = "BILASPUR" },
        new() { Code = 16, StateCode = 2, Name = "CHAMBA" },
        new() { Code = 17, StateCode = 2, Name = "HAMIRPUR" },
        new() { Code = 18, StateCode = 2, Name = "KANGRA" },
        new() { Code = 19, StateCode = 2, Name = "KINNAUR" },
        new() { Code = 20, StateCode = 2, Name = "KULLU" },
        new() { Code = 21, StateCode = 2, Name = "LAHUL AND SPITI" },
        new() { Code = 22, StateCode = 2, Name = "MANDI" },
        new() { Code = 23, StateCode = 2, Name = "SHIMLA" },
        new() { Code = 24, StateCode = 2, Name = "SIRMAUR" },
        new() { Code = 25, StateCode = 2, Name = "SOLAN" },
        new() { Code = 26, StateCode = 2, Name = "UNA" },
        new() { Code = 27, StateCode = 3, Name = "AMRITSAR" },
        new() { Code = 605, StateCode = 3, Name = "BARNALA" },
        new() { Code = 28, StateCode = 3, Name = "BATHINDA" },
        new() { Code = 29, StateCode = 3, Name = "FARIDKOT" },
        new() { Code = 30, StateCode = 3, Name = "FATEHGARH SAHIB" },
        new() { Code = 651, StateCode = 3, Name = "FAZILKA" },
        new() { Code = 31, StateCode = 3, Name = "FEROZEPUR" },
        new() { Code = 32, StateCode = 3, Name = "GURDASPUR" },
        new() { Code = 33, StateCode = 3, Name = "HOSHIARPUR" },
        new() { Code = 34, StateCode = 3, Name = "JALANDHAR" },
        new() { Code = 35, StateCode = 3, Name = "KAPURTHALA" },
        new() { Code = 36, StateCode = 3, Name = "LUDHIANA" },
        new() { Code = 737, StateCode = 3, Name = "MALERKOTLA" },
        new() { Code = 37, StateCode = 3, Name = "MANSA" },
        new() { Code = 38, StateCode = 3, Name = "MOGA" },
        new() { Code = 662, StateCode = 3, Name = "PATHANKOT" },
        new() { Code = 41, StateCode = 3, Name = "PATIALA" },
        new() { Code = 42, StateCode = 3, Name = "RUPNAGAR" },
        new() { Code = 608, StateCode = 3, Name = "S.A.S Nagar" },
        new() { Code = 43, StateCode = 3, Name = "SANGRUR" },
        new() { Code = 40, StateCode = 3, Name = "Shahid Bhagat Singh Nagar" },
        new() { Code = 39, StateCode = 3, Name = "SRI MUKTSAR SAHIB" },
        new() { Code = 609, StateCode = 3, Name = "Tarn Taran" },
        new() { Code = 44, StateCode = 4, Name = "CHANDIGARH" },
        new() { Code = 45, StateCode = 5, Name = "ALMORA" },
        new() { Code = 46, StateCode = 5, Name = "BAGESHWAR" },
        new() { Code = 47, StateCode = 5, Name = "CHAMOLI" },
        new() { Code = 48, StateCode = 5, Name = "CHAMPAWAT" },
        new() { Code = 49, StateCode = 5, Name = "DEHRADUN" },
        new() { Code = 50, StateCode = 5, Name = "HARIDWAR" },
        new() { Code = 51, StateCode = 5, Name = "NAINITAL" },
        new() { Code = 52, StateCode = 5, Name = "PAURI GARHWAL" },
        new() { Code = 53, StateCode = 5, Name = "PITHORAGARH" },
        new() { Code = 54, StateCode = 5, Name = "RUDRA PRAYAG" },
        new() { Code = 55, StateCode = 5, Name = "TEHRI GARHWAL" },
        new() { Code = 56, StateCode = 5, Name = "UDAM SINGH NAGAR" },
        new() { Code = 57, StateCode = 5, Name = "UTTAR KASHI" },
        new() { Code = 58, StateCode = 6, Name = "AMBALA" },
        new() { Code = 59, StateCode = 6, Name = "BHIWANI" },
        new() { Code = 701, StateCode = 6, Name = "CHARKI DADRI" },
        new() { Code = 60, StateCode = 6, Name = "FARIDABAD" },
        new() { Code = 61, StateCode = 6, Name = "FATEHABAD" },
        new() { Code = 62, StateCode = 6, Name = "GURUGRAM" },
        new() { Code = 63, StateCode = 6, Name = "HISAR" },
        new() { Code = 64, StateCode = 6, Name = "JHAJJAR" },
        new() { Code = 65, StateCode = 6, Name = "JIND" },
        new() { Code = 66, StateCode = 6, Name = "KAITHAL" },
        new() { Code = 67, StateCode = 6, Name = "KARNAL" },
        new() { Code = 68, StateCode = 6, Name = "KURUKSHETRA" },
        new() { Code = 69, StateCode = 6, Name = "MAHENDRAGARH" },
        new() { Code = 604, StateCode = 6, Name = "NUH" },
        new() { Code = 619, StateCode = 6, Name = "PALWAL" },
        new() { Code = 70, StateCode = 6, Name = "PANCHKULA" },
        new() { Code = 71, StateCode = 6, Name = "PANIPAT" },
        new() { Code = 72, StateCode = 6, Name = "REWARI" },
        new() { Code = 73, StateCode = 6, Name = "ROHTAK" },
        new() { Code = 74, StateCode = 6, Name = "SIRSA" },
        new() { Code = 75, StateCode = 6, Name = "SONIPAT" },
        new() { Code = 76, StateCode = 6, Name = "YAMUNANAGAR" },
        new() { Code = 77, StateCode = 7, Name = "CENTRAL" },
        new() { Code = 78, StateCode = 7, Name = "EAST" },
        new() { Code = 79, StateCode = 7, Name = "NEW DELHI" },
        new() { Code = 80, StateCode = 7, Name = "NORTH" },
        new() { Code = 81, StateCode = 7, Name = "NORTH EAST" },
        new() { Code = 82, StateCode = 7, Name = "NORTH WEST" },
        new() { Code = 671, StateCode = 7, Name = "SHAHDARA" },
        new() { Code = 83, StateCode = 7, Name = "SOUTH" },
        new() { Code = 670, StateCode = 7, Name = "South East" },
        new() { Code = 84, StateCode = 7, Name = "SOUTH WEST" },
        new() { Code = 85, StateCode = 7, Name = "WEST" },
        new() { Code = 86, StateCode = 8, Name = "AJMER" },
        new() { Code = 87, StateCode = 8, Name = "ALWAR" },
        new() { Code = 88, StateCode = 8, Name = "BANSWARA" },
        new() { Code = 89, StateCode = 8, Name = "BARAN" },
        new() { Code = 90, StateCode = 8, Name = "BARMER" },
        new() { Code = 91, StateCode = 8, Name = "BHARATPUR" },
        new() { Code = 92, StateCode = 8, Name = "BHILWARA" },
        new() { Code = 93, StateCode = 8, Name = "BIKANER" },
        new() { Code = 94, StateCode = 8, Name = "BUNDI" },
        new() { Code = 95, StateCode = 8, Name = "CHITTORGARH" },
        new() { Code = 96, StateCode = 8, Name = "CHURU" },
        new() { Code = 97, StateCode = 8, Name = "DAUSA" },
        new() { Code = 98, StateCode = 8, Name = "DHOLPUR" },
        new() { Code = 99, StateCode = 8, Name = "DUNGARPUR" },
        new() { Code = 100, StateCode = 8, Name = "GANGANAGAR" },
        new() { Code = 101, StateCode = 8, Name = "HANUMANGARH" },
        new() { Code = 102, StateCode = 8, Name = "JAIPUR" },
        new() { Code = 103, StateCode = 8, Name = "JAISALMER" },
        new() { Code = 104, StateCode = 8, Name = "JALORE" },
        new() { Code = 105, StateCode = 8, Name = "JHALAWAR" },
        new() { Code = 106, StateCode = 8, Name = "JHUNJHUNU" },
        new() { Code = 107, StateCode = 8, Name = "JODHPUR" },
        new() { Code = 108, StateCode = 8, Name = "KARAULI" },
        new() { Code = 109, StateCode = 8, Name = "KOTA" },
        new() { Code = 110, StateCode = 8, Name = "NAGAUR" },
        new() { Code = 111, StateCode = 8, Name = "PALI" },
        new() { Code = 629, StateCode = 8, Name = "PRATAPGARH" },
        new() { Code = 112, StateCode = 8, Name = "RAJSAMAND" },
        new() { Code = 113, StateCode = 8, Name = "SAWAI MADHOPUR" },
        new() { Code = 114, StateCode = 8, Name = "SIKAR" },
        new() { Code = 115, StateCode = 8, Name = "SIROHI" },
        new() { Code = 116, StateCode = 8, Name = "TONK" },
        new() { Code = 117, StateCode = 8, Name = "UDAIPUR" },
        new() { Code = 118, StateCode = 9, Name = "AGRA" },
        new() { Code = 119, StateCode = 9, Name = "ALIGARH" },
        new() { Code = 121, StateCode = 9, Name = "AMBEDKAR NAGAR" },
        new() { Code = 640, StateCode = 9, Name = "Amethi" },
        new() { Code = 154, StateCode = 9, Name = "AMROHA" },
        new() { Code = 122, StateCode = 9, Name = "AURAIYA" },
        new() { Code = 140, StateCode = 9, Name = "AYODHYA" },
        new() { Code = 123, StateCode = 9, Name = "AZAMGARH" },
        new() { Code = 124, StateCode = 9, Name = "BAGHPAT" },
        new() { Code = 125, StateCode = 9, Name = "BAHRAICH" },
        new() { Code = 126, StateCode = 9, Name = "BALLIA" },
        new() { Code = 127, StateCode = 9, Name = "BALRAMPUR" },
        new() { Code = 128, StateCode = 9, Name = "BANDA" },
        new() { Code = 129, StateCode = 9, Name = "BARABANKI" },
        new() { Code = 130, StateCode = 9, Name = "BAREILLY" },
        new() { Code = 131, StateCode = 9, Name = "BASTI" },
        new() { Code = 179, StateCode = 9, Name = "BHADOHI" },
        new() { Code = 132, StateCode = 9, Name = "BIJNOR" },
        new() { Code = 133, StateCode = 9, Name = "BUDAUN" },
        new() { Code = 134, StateCode = 9, Name = "BULANDSHAHR" },
        new() { Code = 135, StateCode = 9, Name = "CHANDAULI" },
        new() { Code = 136, StateCode = 9, Name = "CHITRAKOOT" },
        new() { Code = 137, StateCode = 9, Name = "DEORIA" },
        new() { Code = 138, StateCode = 9, Name = "ETAH" },
        new() { Code = 139, StateCode = 9, Name = "ETAWAH" },
        new() { Code = 141, StateCode = 9, Name = "FARRUKHABAD" },
        new() { Code = 142, StateCode = 9, Name = "FATEHPUR" },
        new() { Code = 143, StateCode = 9, Name = "FIROZABAD" },
        new() { Code = 144, StateCode = 9, Name = "GAUTAM BUDDHA NAGAR" },
        new() { Code = 145, StateCode = 9, Name = "GHAZIABAD" },
        new() { Code = 146, StateCode = 9, Name = "GHAZIPUR" },
        new() { Code = 147, StateCode = 9, Name = "GONDA" },
        new() { Code = 148, StateCode = 9, Name = "GORAKHPUR" },
        new() { Code = 149, StateCode = 9, Name = "HAMIRPUR" },
        new() { Code = 661, StateCode = 9, Name = "HAPUR" },
        new() { Code = 150, StateCode = 9, Name = "HARDOI" },
        new() { Code = 163, StateCode = 9, Name = "HATHRAS" },
        new() { Code = 151, StateCode = 9, Name = "JALAUN" },
        new() { Code = 152, StateCode = 9, Name = "JAUNPUR" },
        new() { Code = 153, StateCode = 9, Name = "JHANSI" },
        new() { Code = 155, StateCode = 9, Name = "KANNAUJ" },
        new() { Code = 156, StateCode = 9, Name = "KANPUR DEHAT" },
        new() { Code = 157, StateCode = 9, Name = "KANPUR NAGAR" },
        new() { Code = 633, StateCode = 9, Name = "Kasganj" },
        new() { Code = 158, StateCode = 9, Name = "KAUSHAMBI" },
        new() { Code = 159, StateCode = 9, Name = "KHERI" },
        new() { Code = 160, StateCode = 9, Name = "KUSHI NAGAR" },
        new() { Code = 161, StateCode = 9, Name = "LALITPUR" },
        new() { Code = 162, StateCode = 9, Name = "LUCKNOW" },
        new() { Code = 164, StateCode = 9, Name = "MAHARAJGANJ" },
        new() { Code = 165, StateCode = 9, Name = "MAHOBA" },
        new() { Code = 166, StateCode = 9, Name = "MAINPURI" },
        new() { Code = 167, StateCode = 9, Name = "MATHURA" },
        new() { Code = 168, StateCode = 9, Name = "MAU" },
        new() { Code = 169, StateCode = 9, Name = "MEERUT" },
        new() { Code = 170, StateCode = 9, Name = "MIRZAPUR" },
        new() { Code = 171, StateCode = 9, Name = "MORADABAD" },
        new() { Code = 172, StateCode = 9, Name = "MUZAFFARNAGAR" },
        new() { Code = 173, StateCode = 9, Name = "PILIBHIT" },
        new() { Code = 174, StateCode = 9, Name = "PRATAPGARH" },
        new() { Code = 120, StateCode = 9, Name = "PRAYAGRAJ" },
        new() { Code = 175, StateCode = 9, Name = "RAE BARELI" },
        new() { Code = 176, StateCode = 9, Name = "RAMPUR" },
        new() { Code = 177, StateCode = 9, Name = "SAHARANPUR" },
        new() { Code = 659, StateCode = 9, Name = "SAMBHAL" },
        new() { Code = 178, StateCode = 9, Name = "SANT KABEER NAGAR" },
        new() { Code = 180, StateCode = 9, Name = "SHAHJAHANPUR" },
        new() { Code = 660, StateCode = 9, Name = "SHAMLI" },
        new() { Code = 181, StateCode = 9, Name = "SHRAVASTI" },
        new() { Code = 182, StateCode = 9, Name = "SIDDHARTH NAGAR" },
        new() { Code = 183, StateCode = 9, Name = "SITAPUR" },
        new() { Code = 184, StateCode = 9, Name = "SONBHADRA" },
        new() { Code = 185, StateCode = 9, Name = "SULTANPUR" },
        new() { Code = 186, StateCode = 9, Name = "UNNAO" },
        new() { Code = 187, StateCode = 9, Name = "VARANASI" },
        new() { Code = 188, StateCode = 10, Name = "ARARIA" },
        new() { Code = 611, StateCode = 10, Name = "ARWAL" },
        new() { Code = 189, StateCode = 10, Name = "AURANGABAD" },
        new() { Code = 190, StateCode = 10, Name = "BANKA" },
        new() { Code = 191, StateCode = 10, Name = "BEGUSARAI" },
        new() { Code = 192, StateCode = 10, Name = "BHAGALPUR" },
        new() { Code = 193, StateCode = 10, Name = "BHOJPUR" },
        new() { Code = 194, StateCode = 10, Name = "BUXAR" },
        new() { Code = 195, StateCode = 10, Name = "DARBHANGA" },
        new() { Code = 196, StateCode = 10, Name = "GAYA" },
        new() { Code = 197, StateCode = 10, Name = "GOPALGANJ" },
        new() { Code = 198, StateCode = 10, Name = "JAMUI" },
        new() { Code = 199, StateCode = 10, Name = "JEHANABAD" },
        new() { Code = 200, StateCode = 10, Name = "KAIMUR (BHABUA)" },
        new() { Code = 201, StateCode = 10, Name = "KATIHAR" },
        new() { Code = 202, StateCode = 10, Name = "KHAGARIA" },
        new() { Code = 203, StateCode = 10, Name = "KISHANGANJ" },
        new() { Code = 204, StateCode = 10, Name = "LAKHISARAI" },
        new() { Code = 205, StateCode = 10, Name = "MADHEPURA" },
        new() { Code = 206, StateCode = 10, Name = "MADHUBANI" },
        new() { Code = 207, StateCode = 10, Name = "MUNGER" },
        new() { Code = 208, StateCode = 10, Name = "MUZAFFARPUR" },
        new() { Code = 209, StateCode = 10, Name = "NALANDA" },
        new() { Code = 210, StateCode = 10, Name = "NAWADA" },
        new() { Code = 211, StateCode = 10, Name = "PASHCHIM CHAMPARAN" },
        new() { Code = 212, StateCode = 10, Name = "PATNA" },
        new() { Code = 213, StateCode = 10, Name = "PURBI CHAMPARAN" },
        new() { Code = 214, StateCode = 10, Name = "PURNIA" },
        new() { Code = 215, StateCode = 10, Name = "ROHTAS" },
        new() { Code = 216, StateCode = 10, Name = "SAHARSA" },
        new() { Code = 217, StateCode = 10, Name = "SAMASTIPUR" },
        new() { Code = 218, StateCode = 10, Name = "SARAN" },
        new() { Code = 219, StateCode = 10, Name = "SHEIKHPURA" },
        new() { Code = 220, StateCode = 10, Name = "SHEOHAR" },
        new() { Code = 221, StateCode = 10, Name = "SITAMARHI" },
        new() { Code = 222, StateCode = 10, Name = "SIWAN" },
        new() { Code = 223, StateCode = 10, Name = "SUPAUL" },
        new() { Code = 224, StateCode = 10, Name = "VAISHALI" },
        new() { Code = 225, StateCode = 11, Name = "Gangtok" },
        new() { Code = 228, StateCode = 11, Name = "Gyalshing" },
        new() { Code = 226, StateCode = 11, Name = "Mangan" },
        new() { Code = 227, StateCode = 11, Name = "Namchi" },
        new() { Code = 741, StateCode = 11, Name = "Pakyong" },
        new() { Code = 742, StateCode = 11, Name = "Soreng" },
        new() { Code = 628, StateCode = 12, Name = "ANJAW" },
        new() { Code = 229, StateCode = 12, Name = "CHANGLANG" },
        new() { Code = 230, StateCode = 12, Name = "DIBANG VALLEY" },
        new() { Code = 231, StateCode = 12, Name = "EAST KAMENG" },
        new() { Code = 232, StateCode = 12, Name = "EAST SIANG" },
        new() { Code = 718, StateCode = 12, Name = "KAMLE" },
        new() { Code = 677, StateCode = 12, Name = "KRA DAADI" },
        new() { Code = 233, StateCode = 12, Name = "KURUNG KUMEY" },
        new() { Code = 724, StateCode = 12, Name = "LEPARADA" },
        new() { Code = 234, StateCode = 12, Name = "LOHIT" },
        new() { Code = 666, StateCode = 12, Name = "LONGDING" },
        new() { Code = 235, StateCode = 12, Name = "LOWER DIBANG VALLEY" },
        new() { Code = 719, StateCode = 12, Name = "LOWER SIANG" },
        new() { Code = 236, StateCode = 12, Name = "LOWER SUBANSIRI" },
        new() { Code = 678, StateCode = 12, Name = "NAMSAI" },
        new() { Code = 723, StateCode = 12, Name = "PAKKE KESSANG" },
        new() { Code = 237, StateCode = 12, Name = "PAPUM PARE" },
        new() { Code = 725, StateCode = 12, Name = "SHI YOMI" },
        new() { Code = 679, StateCode = 12, Name = "SIANG" },
        new() { Code = 238, StateCode = 12, Name = "TAWANG" },
        new() { Code = 239, StateCode = 12, Name = "TIRAP" },
        new() { Code = 240, StateCode = 12, Name = "UPPER SIANG" },
        new() { Code = 241, StateCode = 12, Name = "UPPER SUBANSIRI" },
        new() { Code = 242, StateCode = 12, Name = "WEST KAMENG" },
        new() { Code = 243, StateCode = 12, Name = "WEST SIANG" },
        new() { Code = 758, StateCode = 13, Name = "Chumoukedima" },
        new() { Code = 244, StateCode = 13, Name = "DIMAPUR" },
        new() { Code = 614, StateCode = 13, Name = "KIPHIRE" },
        new() { Code = 245, StateCode = 13, Name = "KOHIMA" },
        new() { Code = 615, StateCode = 13, Name = "LONGLENG" },
        new() { Code = 246, StateCode = 13, Name = "MOKOKCHUNG" },
        new() { Code = 247, StateCode = 13, Name = "MON" },
        new() { Code = 736, StateCode = 13, Name = "Noklak" },
        new() { Code = 613, StateCode = 13, Name = "PEREN" },
        new() { Code = 248, StateCode = 13, Name = "PHEK" },
        new() { Code = 757, StateCode = 13, Name = "Tseminyu" },
        new() { Code = 249, StateCode = 13, Name = "TUENSANG" },
        new() { Code = 250, StateCode = 13, Name = "WOKHA" },
        new() { Code = 251, StateCode = 13, Name = "ZUNHEBOTO" },
        new() { Code = 252, StateCode = 14, Name = "BISHNUPUR" },
        new() { Code = 253, StateCode = 14, Name = "CHANDEL" },
        new() { Code = 254, StateCode = 14, Name = "CHURACHANDPUR" },
        new() { Code = 255, StateCode = 14, Name = "IMPHAL EAST" },
        new() { Code = 256, StateCode = 14, Name = "IMPHAL WEST" },
        new() { Code = 713, StateCode = 14, Name = "JIRIBAM" },
        new() { Code = 711, StateCode = 14, Name = "KAKCHING" },
        new() { Code = 717, StateCode = 14, Name = "KAMJONG" },
        new() { Code = 712, StateCode = 14, Name = "KANGPOKPI" },
        new() { Code = 714, StateCode = 14, Name = "NONEY" },
        new() { Code = 715, StateCode = 14, Name = "PHERZAWL" },
        new() { Code = 257, StateCode = 14, Name = "SENAPATI" },
        new() { Code = 258, StateCode = 14, Name = "TAMENGLONG" },
        new() { Code = 716, StateCode = 14, Name = "TENGNOUPAL" },
        new() { Code = 259, StateCode = 14, Name = "THOUBAL" },
        new() { Code = 260, StateCode = 14, Name = "UKHRUL" },
        new() { Code = 261, StateCode = 15, Name = "AIZAWL" },
        new() { Code = 262, StateCode = 15, Name = "CHAMPHAI" },
        new() { Code = 726, StateCode = 15, Name = "Hnahthial" },
        new() { Code = 728, StateCode = 15, Name = "KHAWZAWL" },
        new() { Code = 263, StateCode = 15, Name = "KOLASIB" },
        new() { Code = 264, StateCode = 15, Name = "LAWNGTLAI" },
        new() { Code = 265, StateCode = 15, Name = "LUNGLEI" },
        new() { Code = 266, StateCode = 15, Name = "MAMIT" },
        new() { Code = 267, StateCode = 15, Name = "SAIHA" },
        new() { Code = 727, StateCode = 15, Name = "SAITUAL" },
        new() { Code = 268, StateCode = 15, Name = "SERCHHIP" },
        new() { Code = 269, StateCode = 16, Name = "Dhalai" },
        new() { Code = 654, StateCode = 16, Name = "Gomati" },
        new() { Code = 652, StateCode = 16, Name = "Khowai" },
        new() { Code = 270, StateCode = 16, Name = "North Tripura" },
        new() { Code = 653, StateCode = 16, Name = "Sepahijala" },
        new() { Code = 271, StateCode = 16, Name = "South Tripura" },
        new() { Code = 655, StateCode = 16, Name = "Unakoti" },
        new() { Code = 272, StateCode = 16, Name = "West Tripura" },
        new() { Code = 273, StateCode = 17, Name = "EAST GARO HILLS" },
        new() { Code = 657, StateCode = 17, Name = "EAST JAINTIA HILLS" },
        new() { Code = 274, StateCode = 17, Name = "EAST KHASI HILLS" },
        new() { Code = 740, StateCode = 17, Name = "EASTERN WEST KHASI HILLS" },
        new() { Code = 656, StateCode = 17, Name = "NORTH GARO HILLS" },
        new() { Code = 276, StateCode = 17, Name = "RI BHOI" },
        new() { Code = 277, StateCode = 17, Name = "SOUTH GARO HILLS" },
        new() { Code = 663, StateCode = 17, Name = "SOUTH WEST GARO HILLS" },
        new() { Code = 658, StateCode = 17, Name = "SOUTH WEST KHASI HILLS" },
        new() { Code = 278, StateCode = 17, Name = "WEST GARO HILLS" },
        new() { Code = 275, StateCode = 17, Name = "WEST JAINTIA HILLS" },
        new() { Code = 279, StateCode = 17, Name = "WEST KHASI HILLS" },
        new() { Code = 739, StateCode = 18, Name = "BAJALI" },
        new() { Code = 616, StateCode = 18, Name = "BAKSA" },
        new() { Code = 280, StateCode = 18, Name = "BARPETA" },
        new() { Code = 705, StateCode = 18, Name = "Biswanath" },
        new() { Code = 281, StateCode = 18, Name = "BONGAIGAON" },
        new() { Code = 282, StateCode = 18, Name = "CACHAR" },
        new() { Code = 708, StateCode = 18, Name = "CHARAIDEO" },
        new() { Code = 612, StateCode = 18, Name = "CHIRANG" },
        new() { Code = 283, StateCode = 18, Name = "DARRANG" },
        new() { Code = 284, StateCode = 18, Name = "DHEMAJI" },
        new() { Code = 285, StateCode = 18, Name = "DHUBRI" },
        new() { Code = 286, StateCode = 18, Name = "DIBRUGARH" },
        new() { Code = 299, StateCode = 18, Name = "DIMA HASAO" },
        new() { Code = 287, StateCode = 18, Name = "GOALPARA" },
        new() { Code = 288, StateCode = 18, Name = "GOLAGHAT" },
        new() { Code = 289, StateCode = 18, Name = "HAILAKANDI" },
        new() { Code = 709, StateCode = 18, Name = "HOJAI" },
        new() { Code = 290, StateCode = 18, Name = "JORHAT" },
        new() { Code = 291, StateCode = 18, Name = "KAMRUP" },
        new() { Code = 618, StateCode = 18, Name = "KAMRUP METRO" },
        new() { Code = 292, StateCode = 18, Name = "KARBI ANGLONG" },
        new() { Code = 293, StateCode = 18, Name = "KARIMGANJ" },
        new() { Code = 294, StateCode = 18, Name = "KOKRAJHAR" },
        new() { Code = 295, StateCode = 18, Name = "LAKHIMPUR" },
        new() { Code = 706, StateCode = 18, Name = "MAJULI" },
        new() { Code = 296, StateCode = 18, Name = "MARIGAON" },
        new() { Code = 297, StateCode = 18, Name = "NAGAON" },
        new() { Code = 298, StateCode = 18, Name = "NALBARI" },
        new() { Code = 300, StateCode = 18, Name = "SIVASAGAR" },
        new() { Code = 301, StateCode = 18, Name = "SONITPUR" },
        new() { Code = 707, StateCode = 18, Name = "SOUTH SALMARA MANCACHAR" },
        new() { Code = 756, StateCode = 18, Name = "TAMULPUR" },
        new() { Code = 302, StateCode = 18, Name = "TINSUKIA" },
        new() { Code = 617, StateCode = 18, Name = "UDALGURI" },
        new() { Code = 710, StateCode = 18, Name = "WEST KARBI ANGLONG" },
        new() { Code = 303, StateCode = 19, Name = "24 PARAGANAS NORTH" },
        new() { Code = 304, StateCode = 19, Name = "24 PARAGANAS SOUTH" },
        new() { Code = 664, StateCode = 19, Name = "Alipurduar" },
        new() { Code = 305, StateCode = 19, Name = "BANKURA" },
        new() { Code = 307, StateCode = 19, Name = "BIRBHUM" },
        new() { Code = 308, StateCode = 19, Name = "COOCHBEHAR" },
        new() { Code = 309, StateCode = 19, Name = "DARJEELING" },
        new() { Code = 310, StateCode = 19, Name = "DINAJPUR DAKSHIN" },
        new() { Code = 311, StateCode = 19, Name = "DINAJPUR UTTAR" },
        new() { Code = 312, StateCode = 19, Name = "HOOGHLY" },
        new() { Code = 313, StateCode = 19, Name = "HOWRAH" },
        new() { Code = 314, StateCode = 19, Name = "JALPAIGURI" },
        new() { Code = 703, StateCode = 19, Name = "Jhargram" },
        new() { Code = 702, StateCode = 19, Name = "KALIMPONG" },
        new() { Code = 315, StateCode = 19, Name = "KOLKATA" },
        new() { Code = 316, StateCode = 19, Name = "MALDAH" },
        new() { Code = 317, StateCode = 19, Name = "MEDINIPUR EAST" },
        new() { Code = 318, StateCode = 19, Name = "MEDINIPUR WEST" },
        new() { Code = 319, StateCode = 19, Name = "MURSHIDABAD" },
        new() { Code = 320, StateCode = 19, Name = "NADIA" },
        new() { Code = 704, StateCode = 19, Name = "PASCHIM BARDHAMAN" },
        new() { Code = 306, StateCode = 19, Name = "PURBA BARDHAMAN" },
        new() { Code = 321, StateCode = 19, Name = "PURULIA" },
        new() { Code = 322, StateCode = 20, Name = "BOKARO" },
        new() { Code = 323, StateCode = 20, Name = "CHATRA" },
        new() { Code = 324, StateCode = 20, Name = "DEOGHAR" },
        new() { Code = 325, StateCode = 20, Name = "DHANBAD" },
        new() { Code = 326, StateCode = 20, Name = "DUMKA" },
        new() { Code = 327, StateCode = 20, Name = "EAST SINGHBUM" },
        new() { Code = 328, StateCode = 20, Name = "GARHWA" },
        new() { Code = 329, StateCode = 20, Name = "GIRIDIH" },
        new() { Code = 330, StateCode = 20, Name = "GODDA" },
        new() { Code = 331, StateCode = 20, Name = "GUMLA" },
        new() { Code = 332, StateCode = 20, Name = "HAZARIBAGH" },
        new() { Code = 333, StateCode = 20, Name = "JAMTARA" },
        new() { Code = 606, StateCode = 20, Name = "KHUNTI" },
        new() { Code = 334, StateCode = 20, Name = "KODERMA" },
        new() { Code = 335, StateCode = 20, Name = "LATEHAR" },
        new() { Code = 336, StateCode = 20, Name = "LOHARDAGA" },
        new() { Code = 337, StateCode = 20, Name = "PAKUR" },
        new() { Code = 338, StateCode = 20, Name = "PALAMU" },
        new() { Code = 607, StateCode = 20, Name = "RAMGARH" },
        new() { Code = 339, StateCode = 20, Name = "RANCHI" },
        new() { Code = 340, StateCode = 20, Name = "SAHEBGANJ" },
        new() { Code = 341, StateCode = 20, Name = "SARAIKELA KHARSAWAN" },
        new() { Code = 342, StateCode = 20, Name = "SIMDEGA" },
        new() { Code = 343, StateCode = 20, Name = "WEST SINGHBHUM" },
        new() { Code = 344, StateCode = 21, Name = "ANUGUL" },
        new() { Code = 345, StateCode = 21, Name = "BALANGIR" },
        new() { Code = 346, StateCode = 21, Name = "BALESHWAR" },
        new() { Code = 347, StateCode = 21, Name = "BARGARH" },
        new() { Code = 348, StateCode = 21, Name = "BHADRAK" },
        new() { Code = 349, StateCode = 21, Name = "BOUDH" },
        new() { Code = 350, StateCode = 21, Name = "CUTTACK" },
        new() { Code = 351, StateCode = 21, Name = "DEOGARH" },
        new() { Code = 352, StateCode = 21, Name = "DHENKANAL" },
        new() { Code = 353, StateCode = 21, Name = "GAJAPATI" },
        new() { Code = 354, StateCode = 21, Name = "GANJAM" },
        new() { Code = 355, StateCode = 21, Name = "JAGATSINGHAPUR" },
        new() { Code = 356, StateCode = 21, Name = "JAJAPUR" },
        new() { Code = 357, StateCode = 21, Name = "JHARSUGUDA" },
        new() { Code = 358, StateCode = 21, Name = "KALAHANDI" },
        new() { Code = 359, StateCode = 21, Name = "KANDHAMAL" },
        new() { Code = 360, StateCode = 21, Name = "KENDRAPARA" },
        new() { Code = 361, StateCode = 21, Name = "KENDUJHAR" },
        new() { Code = 362, StateCode = 21, Name = "KHORDHA" },
        new() { Code = 363, StateCode = 21, Name = "KORAPUT" },
        new() { Code = 364, StateCode = 21, Name = "MALKANGIRI" },
        new() { Code = 365, StateCode = 21, Name = "MAYURBHANJ" },
        new() { Code = 366, StateCode = 21, Name = "NABARANGPUR" },
        new() { Code = 367, StateCode = 21, Name = "NAYAGARH" },
        new() { Code = 368, StateCode = 21, Name = "NUAPADA" },
        new() { Code = 369, StateCode = 21, Name = "PURI" },
        new() { Code = 370, StateCode = 21, Name = "RAYAGADA" },
        new() { Code = 371, StateCode = 21, Name = "SAMBALPUR" },
        new() { Code = 372, StateCode = 21, Name = "SONEPUR" },
        new() { Code = 373, StateCode = 21, Name = "SUNDARGARH" },
        new() { Code = 646, StateCode = 22, Name = "BALOD" },
        new() { Code = 644, StateCode = 22, Name = "BALODA BAZAR" },
        new() { Code = 649, StateCode = 22, Name = "BALRAMPUR" },
        new() { Code = 374, StateCode = 22, Name = "BASTAR" },
        new() { Code = 650, StateCode = 22, Name = "BEMETARA" },
        new() { Code = 636, StateCode = 22, Name = "BIJAPUR" },
        new() { Code = 375, StateCode = 22, Name = "BILASPUR" },
        new() { Code = 376, StateCode = 22, Name = "DANTEWADA" },
        new() { Code = 377, StateCode = 22, Name = "DHAMTARI" },
        new() { Code = 378, StateCode = 22, Name = "DURG" },
        new() { Code = 645, StateCode = 22, Name = "GARIYABAND" },
        new() { Code = 734, StateCode = 22, Name = "Gaurella Pendra Marwahi" },
        new() { Code = 379, StateCode = 22, Name = "JANJGIR-CHAMPA" },
        new() { Code = 380, StateCode = 22, Name = "JASHPUR" },
        new() { Code = 382, StateCode = 22, Name = "KABIRDHAM" },
        new() { Code = 381, StateCode = 22, Name = "KANKER" },
        new() { Code = 759, StateCode = 22, Name = "KHAIRGARH CHHUIKHADAN GANDAI" },
        new() { Code = 643, StateCode = 22, Name = "KONDAGAON" },
        new() { Code = 383, StateCode = 22, Name = "KORBA" },
        new() { Code = 384, StateCode = 22, Name = "KOREA" },
        new() { Code = 385, StateCode = 22, Name = "MAHASAMUND" },
        new() { Code = 760, StateCode = 22, Name = "MANENDRAGARH CHIRIMIRI BHARATPUR" },
        new() { Code = 761, StateCode = 22, Name = "MOHLA MANPUR AMBAGARH CHOUKI" },
        new() { Code = 647, StateCode = 22, Name = "MUNGELI" },
        new() { Code = 637, StateCode = 22, Name = "NARAYANPUR" },
        new() { Code = 386, StateCode = 22, Name = "RAIGARH" },
        new() { Code = 387, StateCode = 22, Name = "RAIPUR" },
        new() { Code = 388, StateCode = 22, Name = "RAJNANDGAON" },
        new() { Code = 762, StateCode = 22, Name = "SAKTI" },
        new() { Code = 763, StateCode = 22, Name = "SARANGARH BILAIGARH" },
        new() { Code = 642, StateCode = 22, Name = "SUKMA" },
        new() { Code = 648, StateCode = 22, Name = "SURAJPUR" },
        new() { Code = 389, StateCode = 22, Name = "SURGUJA" },
        new() { Code = 667, StateCode = 23, Name = "AGAR MALWA" },
        new() { Code = 639, StateCode = 23, Name = "ALIRAJPUR" },
        new() { Code = 390, StateCode = 23, Name = "ANUPPUR" },
        new() { Code = 391, StateCode = 23, Name = "ASHOKNAGAR" },
        new() { Code = 392, StateCode = 23, Name = "BALAGHAT" },
        new() { Code = 393, StateCode = 23, Name = "BARWANI" },
        new() { Code = 394, StateCode = 23, Name = "BETUL" },
        new() { Code = 395, StateCode = 23, Name = "BHIND" },
        new() { Code = 396, StateCode = 23, Name = "BHOPAL" },
        new() { Code = 397, StateCode = 23, Name = "BURHANPUR" },
        new() { Code = 398, StateCode = 23, Name = "CHHATARPUR" },
        new() { Code = 399, StateCode = 23, Name = "CHHINDWARA" },
        new() { Code = 400, StateCode = 23, Name = "DAMOH" },
        new() { Code = 401, StateCode = 23, Name = "DATIA" },
        new() { Code = 402, StateCode = 23, Name = "DEWAS" },
        new() { Code = 403, StateCode = 23, Name = "DHAR" },
        new() { Code = 404, StateCode = 23, Name = "DINDORI" },
        new() { Code = 405, StateCode = 23, Name = "EAST NIMAR" },
        new() { Code = 406, StateCode = 23, Name = "GUNA" },
        new() { Code = 407, StateCode = 23, Name = "GWALIOR" },
        new() { Code = 408, StateCode = 23, Name = "HARDA" },
        new() { Code = 410, StateCode = 23, Name = "INDORE" },
        new() { Code = 411, StateCode = 23, Name = "JABALPUR" },
        new() { Code = 412, StateCode = 23, Name = "JHABUA" },
        new() { Code = 413, StateCode = 23, Name = "KATNI" },
        new() { Code = 414, StateCode = 23, Name = "KHARGONE" },
        new() { Code = 415, StateCode = 23, Name = "MANDLA" },
        new() { Code = 416, StateCode = 23, Name = "MANDSAUR" },
        new() { Code = 417, StateCode = 23, Name = "MORENA" },
        new() { Code = 409, StateCode = 23, Name = "NARMADAPURAM" },
        new() { Code = 418, StateCode = 23, Name = "NARSINGHPUR" },
        new() { Code = 419, StateCode = 23, Name = "NEEMUCH" },
        new() { Code = 722, StateCode = 23, Name = "Niwari" },
        new() { Code = 420, StateCode = 23, Name = "PANNA" },
        new() { Code = 421, StateCode = 23, Name = "RAISEN" },
        new() { Code = 422, StateCode = 23, Name = "RAJGARH" },
        new() { Code = 423, StateCode = 23, Name = "RATLAM" },
        new() { Code = 424, StateCode = 23, Name = "REWA" },
        new() { Code = 425, StateCode = 23, Name = "SAGAR" },
        new() { Code = 426, StateCode = 23, Name = "SATNA" },
        new() { Code = 427, StateCode = 23, Name = "SEHORE" },
        new() { Code = 428, StateCode = 23, Name = "SEONI" },
        new() { Code = 429, StateCode = 23, Name = "SHAHDOL" },
        new() { Code = 430, StateCode = 23, Name = "SHAJAPUR" },
        new() { Code = 431, StateCode = 23, Name = "SHEOPUR" },
        new() { Code = 432, StateCode = 23, Name = "SHIVPURI" },
        new() { Code = 433, StateCode = 23, Name = "SIDHI" },
        new() { Code = 638, StateCode = 23, Name = "SINGRAULI" },
        new() { Code = 434, StateCode = 23, Name = "TIKAMGARH" },
        new() { Code = 435, StateCode = 23, Name = "UJJAIN" },
        new() { Code = 436, StateCode = 23, Name = "UMARIA" },
        new() { Code = 437, StateCode = 23, Name = "VIDISHA" },
        new() { Code = 438, StateCode = 24, Name = "AHMADABAD" },
        new() { Code = 439, StateCode = 24, Name = "AMRELI" },
        new() { Code = 440, StateCode = 24, Name = "ANAND" },
        new() { Code = 672, StateCode = 24, Name = "ARVALLI" },
        new() { Code = 441, StateCode = 24, Name = "BANAS KANTHA" },
        new() { Code = 442, StateCode = 24, Name = "BHARUCH" },
        new() { Code = 443, StateCode = 24, Name = "BHAVNAGAR" },
        new() { Code = 676, StateCode = 24, Name = "BOTAD" },
        new() { Code = 668, StateCode = 24, Name = "CHHOTAUDEPUR" },
        new() { Code = 444, StateCode = 24, Name = "DANG" },
        new() { Code = 674, StateCode = 24, Name = "DEVBHUMI DWARKA" },
        new() { Code = 445, StateCode = 24, Name = "DOHAD" },
        new() { Code = 446, StateCode = 24, Name = "GANDHINAGAR" },
        new() { Code = 675, StateCode = 24, Name = "GIR SOMNATH" },
        new() { Code = 447, StateCode = 24, Name = "JAMNAGAR" },
        new() { Code = 448, StateCode = 24, Name = "JUNAGADH" },
        new() { Code = 449, StateCode = 24, Name = "KACHCHH" },
        new() { Code = 450, StateCode = 24, Name = "KHEDA" },
        new() { Code = 451, StateCode = 24, Name = "MAHESANA" },
        new() { Code = 669, StateCode = 24, Name = "Mahisagar" },
        new() { Code = 673, StateCode = 24, Name = "MORBI" },
        new() { Code = 452, StateCode = 24, Name = "NARMADA" },
        new() { Code = 453, StateCode = 24, Name = "NAVSARI" },
        new() { Code = 454, StateCode = 24, Name = "PANCH MAHALS" },
        new() { Code = 455, StateCode = 24, Name = "PATAN" },
        new() { Code = 456, StateCode = 24, Name = "PORBANDAR" },
        new() { Code = 457, StateCode = 24, Name = "RAJKOT" },
        new() { Code = 458, StateCode = 24, Name = "SABAR KANTHA" },
        new() { Code = 459, StateCode = 24, Name = "SURAT" },
        new() { Code = 460, StateCode = 24, Name = "SURENDRANAGAR" },
        new() { Code = 641, StateCode = 24, Name = "TAPI" },
        new() { Code = 461, StateCode = 24, Name = "VADODARA" },
        new() { Code = 462, StateCode = 24, Name = "VALSAD" },
        new() { Code = 466, StateCode = 27, Name = "AHMEDNAGAR" },
        new() { Code = 467, StateCode = 27, Name = "AKOLA" },
        new() { Code = 468, StateCode = 27, Name = "AMRAVATI" },
        new() { Code = 469, StateCode = 27, Name = "AURANGABAD" },
        new() { Code = 470, StateCode = 27, Name = "BEED" },
        new() { Code = 471, StateCode = 27, Name = "BHANDARA" },
        new() { Code = 472, StateCode = 27, Name = "BULDHANA" },
        new() { Code = 473, StateCode = 27, Name = "CHANDRAPUR" },
        new() { Code = 474, StateCode = 27, Name = "DHULE" },
        new() { Code = 475, StateCode = 27, Name = "GADCHIROLI" },
        new() { Code = 476, StateCode = 27, Name = "GONDIA" },
        new() { Code = 477, StateCode = 27, Name = "HINGOLI" },
        new() { Code = 478, StateCode = 27, Name = "JALGAON" },
        new() { Code = 479, StateCode = 27, Name = "JALNA" },
        new() { Code = 480, StateCode = 27, Name = "KOLHAPUR" },
        new() { Code = 481, StateCode = 27, Name = "LATUR" },
        new() { Code = 482, StateCode = 27, Name = "MUMBAI" },
        new() { Code = 483, StateCode = 27, Name = "MUMBAI SUBURBAN" },
        new() { Code = 484, StateCode = 27, Name = "NAGPUR" },
        new() { Code = 485, StateCode = 27, Name = "NANDED" },
        new() { Code = 486, StateCode = 27, Name = "NANDURBAR" },
        new() { Code = 487, StateCode = 27, Name = "NASHIK" },
        new() { Code = 488, StateCode = 27, Name = "OSMANABAD" },
        new() { Code = 665, StateCode = 27, Name = "PALGHAR" },
        new() { Code = 489, StateCode = 27, Name = "PARBHANI" },
        new() { Code = 490, StateCode = 27, Name = "PUNE" },
        new() { Code = 491, StateCode = 27, Name = "RAIGAD" },
        new() { Code = 492, StateCode = 27, Name = "RATNAGIRI" },
        new() { Code = 493, StateCode = 27, Name = "SANGLI" },
        new() { Code = 494, StateCode = 27, Name = "SATARA" },
        new() { Code = 495, StateCode = 27, Name = "SINDHUDURG" },
        new() { Code = 496, StateCode = 27, Name = "SOLAPUR" },
        new() { Code = 497, StateCode = 27, Name = "THANE" },
        new() { Code = 498, StateCode = 27, Name = "WARDHA" },
        new() { Code = 499, StateCode = 27, Name = "WASHIM" },
        new() { Code = 500, StateCode = 27, Name = "YAVATMAL" },
        new() { Code = 745, StateCode = 28, Name = "Alluri Sitharama Raju" },
        new() { Code = 744, StateCode = 28, Name = "Anakapalli" },
        new() { Code = 502, StateCode = 28, Name = "ANANTAPUR" },
        new() { Code = 753, StateCode = 28, Name = "Annamayya" },
        new() { Code = 750, StateCode = 28, Name = "Bapatla" },
        new() { Code = 503, StateCode = 28, Name = "CHITTOOR" },
        new() { Code = 505, StateCode = 28, Name = "EAST GODAVARI" },
        new() { Code = 748, StateCode = 28, Name = "Eluru" },
        new() { Code = 506, StateCode = 28, Name = "GUNTUR" },
        new() { Code = 746, StateCode = 28, Name = "Kakinada" },
        new() { Code = 747, StateCode = 28, Name = "Konaseema" },
        new() { Code = 510, StateCode = 28, Name = "KRISHNA" },
        new() { Code = 511, StateCode = 28, Name = "KURNOOL" },
        new() { Code = 755, StateCode = 28, Name = "Nandyal" },
        new() { Code = 749, StateCode = 28, Name = "NTR" },
        new() { Code = 751, StateCode = 28, Name = "Palnadu" },
        new() { Code = 743, StateCode = 28, Name = "Parvathipuram Manyam" },
        new() { Code = 517, StateCode = 28, Name = "PRAKASAM" },
        new() { Code = 515, StateCode = 28, Name = "SPSR NELLORE" },
        new() { Code = 754, StateCode = 28, Name = "Sri Sathya Sai" },
        new() { Code = 519, StateCode = 28, Name = "SRIKAKULAM" },
        new() { Code = 752, StateCode = 28, Name = "Tirupati" },
        new() { Code = 520, StateCode = 28, Name = "VISAKHAPATANAM" },
        new() { Code = 521, StateCode = 28, Name = "VIZIANAGARAM" },
        new() { Code = 523, StateCode = 28, Name = "WEST GODAVARI" },
        new() { Code = 504, StateCode = 28, Name = "Y.S.R." },
        new() { Code = 524, StateCode = 29, Name = "BAGALKOTE" },
        new() { Code = 528, StateCode = 29, Name = "BALLARI" },
        new() { Code = 527, StateCode = 29, Name = "BELAGAVI" },
        new() { Code = 526, StateCode = 29, Name = "BENGALURU RURAL" },
        new() { Code = 525, StateCode = 29, Name = "BENGALURU URBAN" },
        new() { Code = 529, StateCode = 29, Name = "BIDAR" },
        new() { Code = 531, StateCode = 29, Name = "CHAMARAJANAGARA" },
        new() { Code = 630, StateCode = 29, Name = "CHIKKABALLAPURA" },
        new() { Code = 532, StateCode = 29, Name = "CHIKKAMAGALURU" },
        new() { Code = 533, StateCode = 29, Name = "CHITRADURGA" },
        new() { Code = 534, StateCode = 29, Name = "DAKSHINA KANNADA" },
        new() { Code = 535, StateCode = 29, Name = "DAVANGERE" },
        new() { Code = 536, StateCode = 29, Name = "DHARWAD" },
        new() { Code = 537, StateCode = 29, Name = "GADAG" },
        new() { Code = 539, StateCode = 29, Name = "HASSAN" },
        new() { Code = 540, StateCode = 29, Name = "HAVERI" },
        new() { Code = 538, StateCode = 29, Name = "KALABURAGI" },
        new() { Code = 541, StateCode = 29, Name = "KODAGU" },
        new() { Code = 542, StateCode = 29, Name = "KOLAR" },
        new() { Code = 543, StateCode = 29, Name = "KOPPAL" },
        new() { Code = 544, StateCode = 29, Name = "MANDYA" },
        new() { Code = 545, StateCode = 29, Name = "MYSURU" },
        new() { Code = 546, StateCode = 29, Name = "RAICHUR" },
        new() { Code = 631, StateCode = 29, Name = "RAMANAGARA" },
        new() { Code = 547, StateCode = 29, Name = "SHIVAMOGGA" },
        new() { Code = 548, StateCode = 29, Name = "TUMAKURU" },
        new() { Code = 549, StateCode = 29, Name = "UDUPI" },
        new() { Code = 550, StateCode = 29, Name = "UTTARA KANNADA" },
        new() { Code = 738, StateCode = 29, Name = "VIJAYANAGAR" },
        new() { Code = 530, StateCode = 29, Name = "VIJAYAPURA" },
        new() { Code = 635, StateCode = 29, Name = "YADGIR" },
        new() { Code = 551, StateCode = 30, Name = "NORTH GOA" },
        new() { Code = 552, StateCode = 30, Name = "SOUTH GOA" },
        new() { Code = 553, StateCode = 31, Name = "LAKSHADWEEP DISTRICT" },
        new() { Code = 554, StateCode = 32, Name = "ALAPPUZHA" },
        new() { Code = 555, StateCode = 32, Name = "ERNAKULAM" },
        new() { Code = 556, StateCode = 32, Name = "IDUKKI" },
        new() { Code = 557, StateCode = 32, Name = "KANNUR" },
        new() { Code = 558, StateCode = 32, Name = "KASARAGOD" },
        new() { Code = 559, StateCode = 32, Name = "KOLLAM" },
        new() { Code = 560, StateCode = 32, Name = "KOTTAYAM" },
        new() { Code = 561, StateCode = 32, Name = "KOZHIKODE" },
        new() { Code = 562, StateCode = 32, Name = "MALAPPURAM" },
        new() { Code = 563, StateCode = 32, Name = "PALAKKAD" },
        new() { Code = 564, StateCode = 32, Name = "PATHANAMTHITTA" },
        new() { Code = 565, StateCode = 32, Name = "THIRUVANANTHAPURAM" },
        new() { Code = 566, StateCode = 32, Name = "THRISSUR" },
        new() { Code = 567, StateCode = 32, Name = "WAYANAD" },
        new() { Code = 610, StateCode = 33, Name = "Ariyalur" },
        new() { Code = 730, StateCode = 33, Name = "CHENGALPATTU" },
        new() { Code = 568, StateCode = 33, Name = "CHENNAI" },
        new() { Code = 569, StateCode = 33, Name = "COIMBATORE" },
        new() { Code = 570, StateCode = 33, Name = "CUDDALORE" },
        new() { Code = 571, StateCode = 33, Name = "DHARMAPURI" },
        new() { Code = 572, StateCode = 33, Name = "DINDIGUL" },
        new() { Code = 573, StateCode = 33, Name = "ERODE" },
        new() { Code = 729, StateCode = 33, Name = "KALLAKURICHI" },
        new() { Code = 574, StateCode = 33, Name = "KANCHIPURAM" },
        new() { Code = 575, StateCode = 33, Name = "KANNIYAKUMARI" },
        new() { Code = 576, StateCode = 33, Name = "KARUR" },
        new() { Code = 577, StateCode = 33, Name = "KRISHNAGIRI" },
        new() { Code = 578, StateCode = 33, Name = "MADURAI" },
        new() { Code = 735, StateCode = 33, Name = "Mayiladuthurai" },
        new() { Code = 579, StateCode = 33, Name = "NAGAPATTINAM" },
        new() { Code = 580, StateCode = 33, Name = "NAMAKKAL" },
        new() { Code = 581, StateCode = 33, Name = "PERAMBALUR" },
        new() { Code = 582, StateCode = 33, Name = "PUDUKKOTTAI" },
        new() { Code = 583, StateCode = 33, Name = "RAMANATHAPURAM" },
        new() { Code = 731, StateCode = 33, Name = "Ranipet" },
        new() { Code = 584, StateCode = 33, Name = "SALEM" },
        new() { Code = 585, StateCode = 33, Name = "SIVAGANGA" },
        new() { Code = 733, StateCode = 33, Name = "TENKASI" },
        new() { Code = 586, StateCode = 33, Name = "THANJAVUR" },
        new() { Code = 587, StateCode = 33, Name = "THE NILGIRIS" },
        new() { Code = 588, StateCode = 33, Name = "THENI" },
        new() { Code = 589, StateCode = 33, Name = "THIRUVALLUR" },
        new() { Code = 590, StateCode = 33, Name = "THIRUVARUR" },
        new() { Code = 591, StateCode = 33, Name = "TIRUCHIRAPPALLI" },
        new() { Code = 592, StateCode = 33, Name = "TIRUNELVELI" },
        new() { Code = 732, StateCode = 33, Name = "Tirupathur" },
        new() { Code = 634, StateCode = 33, Name = "TIRUPPUR" },
        new() { Code = 593, StateCode = 33, Name = "TIRUVANNAMALAI" },
        new() { Code = 594, StateCode = 33, Name = "TUTICORIN" },
        new() { Code = 595, StateCode = 33, Name = "VELLORE" },
        new() { Code = 596, StateCode = 33, Name = "VILLUPURAM" },
        new() { Code = 597, StateCode = 33, Name = "VIRUDHUNAGAR" },
        new() { Code = 598, StateCode = 34, Name = "KARAIKAL" },
        new() { Code = 599, StateCode = 34, Name = "MAHE" },
        new() { Code = 600, StateCode = 34, Name = "PONDICHERRY" },
        new() { Code = 601, StateCode = 34, Name = "YANAM" },
        new() { Code = 603, StateCode = 35, Name = "NICOBARS" },
        new() { Code = 632, StateCode = 35, Name = "NORTH AND MIDDLE ANDAMAN" },
        new() { Code = 602, StateCode = 35, Name = "SOUTH ANDAMANS" },
        new() { Code = 501, StateCode = 36, Name = "ADILABAD" },
        new() { Code = 690, StateCode = 36, Name = "BHADRADRI KOTHAGUDEM" },
        new() { Code = 686, StateCode = 36, Name = "HANUMAKONDA" },
        new() { Code = 507, StateCode = 36, Name = "HYDERABAD" },
        new() { Code = 681, StateCode = 36, Name = "Jagitial" },
        new() { Code = 689, StateCode = 36, Name = "JANGOAN" },
        new() { Code = 687, StateCode = 36, Name = "JAYASHANKAR BHUPALAPALLY" },
        new() { Code = 695, StateCode = 36, Name = "JOGULAMBA GADWAL" },
        new() { Code = 685, StateCode = 36, Name = "KAMAREDDY" },
        new() { Code = 508, StateCode = 36, Name = "KARIMNAGAR" },
        new() { Code = 509, StateCode = 36, Name = "KHAMMAM" },
        new() { Code = 699, StateCode = 36, Name = "KUMURAM BHEEM ASIFABAD" },
        new() { Code = 688, StateCode = 36, Name = "MAHABUBABAD" },
        new() { Code = 512, StateCode = 36, Name = "MAHABUBNAGAR" },
        new() { Code = 684, StateCode = 36, Name = "MANCHERIAL" },
        new() { Code = 513, StateCode = 36, Name = "MEDAK" },
        new() { Code = 700, StateCode = 36, Name = "MEDCHAL MALKAJGIRI" },
        new() { Code = 720, StateCode = 36, Name = "Mulugu" },
        new() { Code = 694, StateCode = 36, Name = "NAGARKURNOOL" },
        new() { Code = 514, StateCode = 36, Name = "NALGONDA" },
        new() { Code = 721, StateCode = 36, Name = "Narayanpet" },
        new() { Code = 680, StateCode = 36, Name = "Nirmal" },
        new() { Code = 516, StateCode = 36, Name = "NIZAMABAD" },
        new() { Code = 682, StateCode = 36, Name = "PEDDAPALLI" },
        new() { Code = 683, StateCode = 36, Name = "RAJANNA SIRCILLA" },
        new() { Code = 518, StateCode = 36, Name = "RANGA REDDY" },
        new() { Code = 691, StateCode = 36, Name = "SANGAREDDY" },
        new() { Code = 692, StateCode = 36, Name = "SIDDIPET" },
        new() { Code = 696, StateCode = 36, Name = "SURYAPET" },
        new() { Code = 698, StateCode = 36, Name = "VIKARABAD" },
        new() { Code = 693, StateCode = 36, Name = "WANAPARTHY" },
        new() { Code = 522, StateCode = 36, Name = "WARANGAL" },
        new() { Code = 697, StateCode = 36, Name = "YADADRI BHUVANAGIRI" },
        new() { Code = 6, StateCode = 37, Name = "KARGIL" },
        new() { Code = 9, StateCode = 37, Name = "LEH LADAKH" },
        new() { Code = 465, StateCode = 38, Name = "DADRA AND NAGAR HAVELI" },
        new() { Code = 463, StateCode = 38, Name = "DAMAN" },
        new() { Code = 464, StateCode = 38, Name = "DIU" },
    ];
}
