<#
.SYNOPSIS
    Builds a signed release APK for the applicant app, the coordinator app, or
    both.

.DESCRIPTION
    Runs entirely on this machine: no Expo account, no EAS, nothing uploaded.

    The API address is injected at build time rather than read from app.json.
    app.json holds the development default, which is localhost, and an APK
    built with that in it is a silent failure — it installs, it opens, and
    every request dies on the device with nothing on the server to show for it.

    The native project is regenerated from the Expo config on every run
    (`expo prebuild --clean`), so android/ is disposable and nothing built by
    hand survives to drift. The signing configuration is therefore re-applied
    each time, from the properties file 02-keystore.ps1 wrote.

.PARAMETER App
    applicant, coordinator, or both. Default both.

.PARAMETER ApiBaseUrl
    What the app talks to. Must be reachable from a phone on mobile data, which
    localhost and a private address are not.

.PARAMETER OutputDir
    Where the APKs are copied. Default E:\cbms-apk.

.EXAMPLE
    .\03-build-apk.ps1
    .\03-build-apk.ps1 -App coordinator -ApiBaseUrl https://leanstaging.qci.org.in/api
#>
[CmdletBinding()]
param(
    [ValidateSet('applicant', 'coordinator', 'both')]
    [string] $App = 'both',
    [string] $ApiBaseUrl = 'https://leanstaging.qci.org.in/api',
    [string] $SourcePath = 'E:\NDIE-Capacity-Building-main',
    [string] $OutputDir = 'E:\cbms-apk',
    [string] $KeystoreDir = 'E:\cbms-keystores',
    [int] $VersionCode = 0,
    [switch] $KeepNativeProject
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '..\windows\_common.ps1')

$started = Get-Date

# --- Sanity ------------------------------------------------------------------

if (-not $env:JAVA_HOME) { throw "JAVA_HOME is not set. Run .\01-prerequisites.ps1." }
$sdk = if ($env:ANDROID_HOME) { $env:ANDROID_HOME } else { $env:ANDROID_SDK_ROOT }
if (-not $sdk -or -not (Test-Path $sdk)) { throw "ANDROID_HOME is not set. Run .\01-prerequisites.ps1." }

# A phone is not on this machine's loopback and, on mobile data, not on its
# network either. Catching it here saves building an APK that cannot work.
if ($ApiBaseUrl -match 'localhost|127\.0\.0\.1|10\.0\.2\.2') {
    throw ("-ApiBaseUrl is $ApiBaseUrl, which no phone can reach. " +
        "Use the public address, e.g. https://leanstaging.qci.org.in/api")
}
if ($ApiBaseUrl -notmatch '/api/?$') {
    throw "-ApiBaseUrl should end in /api, e.g. https://leanstaging.qci.org.in/api"
}
if ($ApiBaseUrl -like 'http://*') {
    # Android has blocked cleartext by default since API 28, so this would not
    # merely be insecure - every request would fail.
    throw "-ApiBaseUrl must be https. Android blocks cleartext traffic by default."
}

$apps = @{
    applicant   = @{ Dir = 'mobile'; Label = 'CBMS Applicant' }
    coordinator = @{ Dir = 'mobile-coordinator'; Label = 'CBMS Coordinator' }
}
$targets = if ($App -eq 'both') { @('applicant', 'coordinator') } else { @($App) }

if (-not (Test-Path $OutputDir)) { New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null }

# --- The build number --------------------------------------------------------

# Android refuses to install an APK whose versionCode is not higher than the
# one already on the device, and the failure on the phone says only "app not
# installed". Kept here rather than in the repository so two builds of the same
# commit still differ.
$counterFile = Join-Path $OutputDir 'versioncode.txt'
if ($VersionCode -le 0) {
    $previous = 0
    if (Test-Path $counterFile) { [int]::TryParse((Get-Content $counterFile -Raw).Trim(), [ref] $previous) | Out-Null }
    $VersionCode = $previous + 1
}
Set-PlainTextFile -Path $counterFile -Content ([string] $VersionCode)

Write-Host "`nBuilding Android release APKs" -ForegroundColor Cyan
Write-Host ("  API          : {0}" -f $ApiBaseUrl) -ForegroundColor Gray
Write-Host ("  versionCode  : {0}" -f $VersionCode) -ForegroundColor Gray
Write-Host ("  output       : {0}`n" -f $OutputDir) -ForegroundColor Gray

# --- Signing -----------------------------------------------------------------

function Add-SigningConfig {
    <#
        The Expo template signs a release build with the debug key. That APK
        installs perfectly well, which is the problem: without this the script
        would hand back something that looks finished, cannot be published, and
        cannot be upgraded by a properly signed build later.

        The generated file is regenerated by every prebuild, so this is applied
        every run. It reads the password from a file whose path comes through
        the environment - nothing secret goes on a command line, where the
        process list would show it.
    #>
    param([string] $GradlePath)

    # ReadAllText detects and strips a byte order mark; Get-Content without an
    # -Encoding falls back to the ANSI code page on a file that has none, which
    # turns a mark into three literal characters instead of removing it. The
    # TrimStart is belt and braces for a mark arriving some other way: whatever
    # is in front of "apply plugin", Groovy will not compile it.
    $gradle = [System.IO.File]::ReadAllText($GradlePath).TrimStart([char] 0xFEFF)

    if ($gradle -notmatch '(?s)signingConfigs\s*\{') {
        throw "No signingConfigs block in $GradlePath. The Expo template has changed; this script needs updating rather than working around."
    }

    $release = @'
        release {
            // Injected by deploy/android/03-build-apk.ps1
            def cbmsProps = new Properties()
            def cbmsPath = System.getenv('CBMS_SIGNING_PROPERTIES')
            if (cbmsPath == null) {
                throw new GradleException('CBMS_SIGNING_PROPERTIES is not set.')
            }
            file(cbmsPath).withInputStream { cbmsProps.load(it) }
            storeFile file(cbmsProps['storeFile'])
            storePassword cbmsProps['storePassword']
            keyAlias cbmsProps['keyAlias']
            keyPassword cbmsProps['keyPassword']
        }
'@

    $gradle = [regex]::Replace(
        $gradle, '(signingConfigs\s*\{)', ('$1' + "`n" + $release), 'None', [TimeSpan]::FromSeconds(5))

    # Only the release buildType. The debug one keeps the debug key, which is
    # what makes a debug build installable alongside nothing in particular.
    $buildTypes = [regex]::Match($gradle, '(?s)buildTypes\s*\{.*')
    if (-not $buildTypes.Success) { throw "No buildTypes block in $GradlePath." }

    $patchedTail = [regex]::Replace(
        $buildTypes.Value,
        '(?s)(release\s*\{[^}]*?signingConfig\s+signingConfigs\.)debug',
        '${1}release', 'None', [TimeSpan]::FromSeconds(5))

    if ($patchedTail -eq $buildTypes.Value) {
        throw ("Could not point the release build at the release key in $GradlePath. " +
            "Refusing to carry on: the APK would be signed with the debug key and " +
            "could never be updated by a properly signed one.")
    }

    $gradle = $gradle.Substring(0, $buildTypes.Index) + $patchedTail
    # No BOM: Groovy refuses a build file that starts with one, and the error
    # it gives — "Unexpected character: '?' at line 1, column 1" — looks like a
    # corrupted file rather than an encoding.
    Set-PlainTextFile -Path $GradlePath -Content $gradle

    # Checked rather than assumed, because this failed twice and the second
    # time the cause was not where the first one had been. Gradle takes seven
    # minutes to reach this file; knowing now beats knowing then.
    $head = [System.IO.File]::ReadAllBytes($GradlePath) | Select-Object -First 8
    if ($head[0] -eq 0xEF -and $head[1] -eq 0xBB -and $head[2] -eq 0xBF) {
        throw ("$GradlePath still begins with a byte order mark: " +
            (($head | ForEach-Object { $_.ToString('X2') }) -join ' '))
    }
    Write-Host ("  [ok]  build.gradle starts {0}" -f `
        (($head | Select-Object -First 4 | ForEach-Object { $_.ToString('X2') }) -join ' ')) -ForegroundColor Gray
}

function Remove-Tree {
    <#
        Gradle keeps handles on files under android/ for a moment after it
        exits, so a delete can fail — and the previous version swallowed that
        with -ErrorAction SilentlyContinue. The folder then survived into the
        next run carrying the file that had just failed to build, which is why
        the same error came back after it had been fixed.
    #>
    param([string] $Path, [switch] $Tolerate)

    if (-not (Test-Path $Path)) { return $true }

    for ($attempt = 1; $attempt -le 5; $attempt++) {
        try {
            Remove-Item $Path -Recurse -Force -ErrorAction Stop
            return $true
        }
        catch {
            if ($attempt -eq 5) {
                if ($Tolerate) {
                    Write-Host ("  [warn] Could not remove {0}: {1}" -f $Path, $_.Exception.Message) -ForegroundColor Yellow
                    Write-Host "         It is rebuilt from scratch next run, so this is untidy rather than wrong." -ForegroundColor Gray
                    return $false
                }
                throw ("Could not remove $Path after 5 attempts: $($_.Exception.Message)`n" +
                    "Something is holding a file open — a Gradle daemon, an editor, or Explorer. " +
                    "Close it, or run: Get-Process java | Stop-Process")
            }
            Start-Sleep -Seconds 2
        }
    }
}

# --- Build -------------------------------------------------------------------

$built = @()

foreach ($name in $targets) {
    $spec = $apps[$name]
    $projectPath = Join-Path $SourcePath $spec.Dir
    if (-not (Test-Path $projectPath)) { throw "Not found: $projectPath. Check -SourcePath." }

    $signingProps = Join-Path $KeystoreDir "$name-signing.properties"
    if (-not (Test-Path $signingProps)) {
        throw "No signing key for $name. Run .\02-keystore.ps1 -App $name first."
    }

    Write-Host ("--- {0} ---" -f $spec.Label) -ForegroundColor Cyan

    Push-Location $projectPath
    try {
        if (-not (Test-Path (Join-Path $projectPath 'node_modules\.package-lock.json'))) {
            Write-Host "  Installing dependencies (first run only)..." -ForegroundColor Gray
            Invoke-Native "npm ci ($name)" 'npm' @('ci', '--no-audit', '--no-fund') -Stream
        }

        # These are read by app.config.js, which is what puts them into the
        # binary. Set for this process only.
        $env:CBMS_API_BASE_URL = $ApiBaseUrl
        $env:CBMS_ANDROID_VERSION_CODE = [string] $VersionCode
        $env:CBMS_SIGNING_PROPERTIES = $signingProps

        # Before prebuild as well as after. --clean is supposed to replace
        # android/, but a folder left behind by a failed run can survive it in
        # part, and then the build is against a mixture of two attempts. This
        # throws rather than continuing, because "mostly regenerated" is the
        # state that produces errors nobody can reproduce.
        Remove-Tree (Join-Path $projectPath 'android') | Out-Null

        Write-Host "  Generating the native project..." -ForegroundColor Gray
        Invoke-Native "expo prebuild ($name)" 'npx' @(
            'expo', 'prebuild', '--platform', 'android', '--clean', '--no-install') -Stream

        $androidPath = Join-Path $projectPath 'android'
        if (-not (Test-Path $androidPath)) { throw "expo prebuild produced no android/ folder." }

        # Gradle finds the SDK through this or through ANDROID_HOME; writing it
        # removes the difference between a shell that has the variable and a
        # service account that does not.
        # No BOM: java.util.Properties would read the mark as part of the first
        # key, so sdk.dir would become a key nobody looks up.
        Set-PlainTextFile -Path (Join-Path $androidPath 'local.properties') `
            -Content ("sdk.dir=" + ($sdk -replace '\\', '\\\\'))

        Add-SigningConfig -GradlePath (Join-Path $androidPath 'app\build.gradle')
        Write-Host "  [ok]  Release signing configured" -ForegroundColor Green

        Write-Host "  Gradle assembleRelease — the first run downloads Gradle and the SDK bits..." -ForegroundColor Gray
        Push-Location $androidPath
        try {
            Invoke-Native "gradle assembleRelease ($name)" (Join-Path $androidPath 'gradlew.bat') @(
                'assembleRelease', '--no-daemon') -Stream
        }
        finally { Pop-Location }

        $apk = Join-Path $androidPath 'app\build\outputs\apk\release\app-release.apk'
        if (-not (Test-Path $apk)) { throw "Gradle reported success but there is no APK at $apk." }

        $stamp = Get-Date -Format 'yyyyMMdd'
        $target = Join-Path $OutputDir ("cbms-{0}-v{1}-{2}.apk" -f $name, $VersionCode, $stamp)
        Copy-Item $apk $target -Force

        $size = [Math]::Round((Get-Item $target).Length / 1MB, 1)
        Write-Host ("  [ok]  {0}  ({1} MB)" -f $target, $size) -ForegroundColor Green
        $built += $target
    }
    finally {
        Pop-Location
        Remove-Item Env:\CBMS_API_BASE_URL -ErrorAction SilentlyContinue
        Remove-Item Env:\CBMS_ANDROID_VERSION_CODE -ErrorAction SilentlyContinue
        Remove-Item Env:\CBMS_SIGNING_PROPERTIES -ErrorAction SilentlyContinue

        if (-not $KeepNativeProject) {
            # Regenerated every run, so leaving it behind only invites someone
            # to edit it and lose the change at the next build. Tolerated here
            # because this runs in a finally block, where throwing would hide
            # whatever sent us here — the next run removes it before prebuild
            # and does not tolerate a failure then.
            Remove-Tree (Join-Path $projectPath 'android') -Tolerate | Out-Null
        }
    }
}

# --- Report ------------------------------------------------------------------

Write-Host ("`nDone in {0:n0}s.`n" -f ((Get-Date) - $started).TotalSeconds) -ForegroundColor Green
foreach ($file in $built) { Write-Host ("  {0}" -f $file) -ForegroundColor White }

Write-Host "`nTo put one on a phone:" -ForegroundColor Cyan
Write-Host "  copy the file across and open it, allowing installation from this source; or" -ForegroundColor Gray
Write-Host "  with the phone plugged in and USB debugging on:" -ForegroundColor Gray
Write-Host ("    & `"{0}\platform-tools\adb.exe`" install -r `"<apk>`"" -f $sdk) -ForegroundColor Gray
Write-Host ""
Write-Host "These are signed with the CBMS release key, so a later build upgrades them" -ForegroundColor Gray
Write-Host "in place. Both apps talk to $ApiBaseUrl." -ForegroundColor Gray
Write-Host ""
