<#
.SYNOPSIS
    Builds a signed release APK for the applicant app, the coordinator app, or
    both.

.DESCRIPTION
    Runs entirely on this machine: no Expo account, no EAS, nothing uploaded.

    The API address is injected at build time rather than read from app.json.
    app.json holds the development default, which is localhost, and an APK
    built with that in it is a silent failure — it installs, it opens, and
    every request dies on the device with nothing on the server to show for it.

    The native project is regenerated from the Expo config on every run
    (`expo prebuild --clean`), so android/ is disposable and nothing built by
    hand survives to drift. The signing configuration is therefore re-applied
    each time, from the properties file 02-keystore.ps1 wrote.

.PARAMETER App
    applicant, coordinator, or both. Default both.

.PARAMETER ApiBaseUrl
    What the app talks to. Must be reachable from a phone on mobile data, which
    localhost and a private address are not.

.PARAMETER OutputDir
    Where the APKs are copied. Default E:\cbms-apk.

.EXAMPLE
    .\03-build-apk.ps1
    .\03-build-apk.ps1 -App coordinator -ApiBaseUrl https://leanstaging.qci.org.in/api
#>
[CmdletBinding()]
param(
    [ValidateSet('applicant', 'coordinator', 'both')]
    [string] $App = 'both',
    [string] $ApiBaseUrl = 'https://leanstaging.qci.org.in/api',
    [string] $SourcePath = 'E:\NDIE-Capacity-Building-main',
    [string] $OutputDir = 'E:\cbms-apk',
    [string] $KeystoreDir = 'E:\cbms-keystores',
    [int] $VersionCode = 0,
    # Where the C++ build tree goes. Short on purpose — see Add-ShortBuildTree.
    [string] $NativeBuildRoot = 'C:\cbms-cxx',
    [switch] $KeepNativeProject
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '..\windows\_common.ps1')

$started = Get-Date

# --- Sanity ------------------------------------------------------------------

if (-not $env:JAVA_HOME) { throw "JAVA_HOME is not set. Run .\01-prerequisites.ps1." }
$sdk = if ($env:ANDROID_HOME) { $env:ANDROID_HOME } else { $env:ANDROID_SDK_ROOT }
if (-not $sdk -or -not (Test-Path $sdk)) { throw "ANDROID_HOME is not set. Run .\01-prerequisites.ps1." }

# A phone is not on this machine's loopback and, on mobile data, not on its
# network either. Catching it here saves building an APK that cannot work.
if ($ApiBaseUrl -match 'localhost|127\.0\.0\.1|10\.0\.2\.2') {
    throw ("-ApiBaseUrl is $ApiBaseUrl, which no phone can reach. " +
        "Use the public address, e.g. https://leanstaging.qci.org.in/api")
}
if ($ApiBaseUrl -notmatch '/api/?$') {
    throw "-ApiBaseUrl should end in /api, e.g. https://leanstaging.qci.org.in/api"
}
if ($ApiBaseUrl -like 'http://*') {
    # Android has blocked cleartext by default since API 28, so this would not
    # merely be insecure - every request would fail.
    throw "-ApiBaseUrl must be https. Android blocks cleartext traffic by default."
}

$apps = @{
    applicant   = @{ Dir = 'mobile'; Label = 'CBMS Applicant' }
    coordinator = @{ Dir = 'mobile-coordinator'; Label = 'CBMS Coordinator' }
}
$targets = if ($App -eq 'both') { @('applicant', 'coordinator') } else { @($App) }

if (-not (Test-Path $OutputDir)) { New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null }

# --- The build number --------------------------------------------------------

# Android refuses to install an APK whose versionCode is not higher than the
# one already on the device, and the failure on the phone says only "app not
# installed". Kept here rather than in the repository so two builds of the same
# commit still differ.
$counterFile = Join-Path $OutputDir 'versioncode.txt'
if ($VersionCode -le 0) {
    $previous = 0
    if (Test-Path $counterFile) { [int]::TryParse((Get-Content $counterFile -Raw).Trim(), [ref] $previous) | Out-Null }
    $VersionCode = $previous + 1
}
Set-PlainTextFile -Path $counterFile -Content ([string] $VersionCode)

Write-Host "`nBuilding Android release APKs" -ForegroundColor Cyan
Write-Host ("  API          : {0}" -f $ApiBaseUrl) -ForegroundColor Gray
Write-Host ("  versionCode  : {0}" -f $VersionCode) -ForegroundColor Gray
Write-Host ("  output       : {0}`n" -f $OutputDir) -ForegroundColor Gray

# --- Signing -----------------------------------------------------------------

function Add-SigningConfig {
    <#
        The Expo template signs a release build with the debug key. That APK
        installs perfectly well, which is the problem: without this the script
        would hand back something that looks finished, cannot be published, and
        cannot be upgraded by a properly signed build later.

        The generated file is regenerated by every prebuild, so this is applied
        every run. It reads the password from a file whose path comes through
        the environment - nothing secret goes on a command line, where the
        process list would show it.
    #>
    param([string] $GradlePath)

    # ReadAllText detects and strips a byte order mark; Get-Content without an
    # -Encoding falls back to the ANSI code page on a file that has none, which
    # turns a mark into three literal characters instead of removing it. The
    # TrimStart is belt and braces for a mark arriving some other way: whatever
    # is in front of "apply plugin", Groovy will not compile it.
    $gradle = [System.IO.File]::ReadAllText($GradlePath).TrimStart([char] 0xFEFF)

    if ($gradle -notmatch '(?s)signingConfigs\s*\{') {
        throw "No signingConfigs block in $GradlePath. The Expo template has changed; this script needs updating rather than working around."
    }

    $release = @'
        release {
            // Injected by deploy/android/03-build-apk.ps1
            def cbmsProps = new Properties()
            def cbmsPath = System.getenv('CBMS_SIGNING_PROPERTIES')
            if (cbmsPath == null) {
                throw new GradleException('CBMS_SIGNING_PROPERTIES is not set.')
            }
            file(cbmsPath).withInputStream { cbmsProps.load(it) }
            storeFile file(cbmsProps['storeFile'])
            storePassword cbmsProps['storePassword']
            keyAlias cbmsProps['keyAlias']
            keyPassword cbmsProps['keyPassword']
        }
'@

    $gradle = [regex]::Replace(
        $gradle, '(signingConfigs\s*\{)', ('$1' + "`n" + $release), 'None', [TimeSpan]::FromSeconds(5))

    # Only the release buildType. The debug one keeps the debug key, which is
    # what makes a debug build installable alongside nothing in particular.
    $buildTypes = [regex]::Match($gradle, '(?s)buildTypes\s*\{.*')
    if (-not $buildTypes.Success) { throw "No buildTypes block in $GradlePath." }

    $patchedTail = [regex]::Replace(
        $buildTypes.Value,
        '(?s)(release\s*\{[^}]*?signingConfig\s+signingConfigs\.)debug',
        '${1}release', 'None', [TimeSpan]::FromSeconds(5))

    if ($patchedTail -eq $buildTypes.Value) {
        throw ("Could not point the release build at the release key in $GradlePath. " +
            "Refusing to carry on: the APK would be signed with the debug key and " +
            "could never be updated by a properly signed one.")
    }

    $gradle = $gradle.Substring(0, $buildTypes.Index) + $patchedTail
    # No BOM: Groovy refuses a build file that starts with one, and the error
    # it gives — "Unexpected character: '?' at line 1, column 1" — looks like a
    # corrupted file rather than an encoding.
    Set-PlainTextFile -Path $GradlePath -Content $gradle

    # Checked rather than assumed, because this failed twice and the second
    # time the cause was not where the first one had been. Gradle takes seven
    # minutes to reach this file; knowing now beats knowing then.
    $head = [System.IO.File]::ReadAllBytes($GradlePath) | Select-Object -First 8
    if ($head[0] -eq 0xEF -and $head[1] -eq 0xBB -and $head[2] -eq 0xBF) {
        throw ("$GradlePath still begins with a byte order mark: " +
            (($head | ForEach-Object { $_.ToString('X2') }) -join ' '))
    }
    Write-Host ("  [ok]  build.gradle starts {0}" -f `
        (($head | Select-Object -First 4 | ForEach-Object { $_.ToString('X2') }) -join ' ')) -ForegroundColor Gray
}

function Add-ShortBuildTree {
    <#
    .SYNOPSIS
        Moves the C++ build tree somewhere short enough for Windows.

    .DESCRIPTION
        CMake names an object file by mirroring the whole absolute source path
        underneath the object directory. For react-native-gesture-handler that
        mirrored tail is about 175 characters on its own, and the object
        directory it sits under —

            <project>/android/app/.cxx/RelWithDebInfo/<hash>/<abi>/
            rngesturehandler_codegen_autolinked_build/CMakeFiles/
            react_codegen_rngesturehandler_codegen.dir/

        — is another 180. Ninja then refuses: "Filename longer than 260
        characters".

        CMAKE_OBJECT_PATH_MAX is meant to solve this by hashing the mirrored
        tail instead, and it does — but only when the directory itself leaves
        room for a name. At 180 characters against a 240 limit there is no
        room, so CMake warns that the object "cannot be safely placed under
        this directory" and writes the long name anyway.

        So the directory has to shrink, and buildStagingDirectory is what moves
        it. C:\cbms-cxx\<app> in place of the project folder takes the
        directory from about 180 characters to about 120, which is enough for
        CMake to fit a hashed name under it — and the build goes through.

        Nothing of value lives there: it is object files, regenerated whenever
        the native project is.
    #>
    param(
        [Parameter(Mandatory)] [string] $GradlePath,
        [Parameter(Mandatory)] [string] $Root,
        [Parameter(Mandatory)] [string] $Name
    )

    $gradle = [System.IO.File]::ReadAllText($GradlePath).TrimStart([char] 0xFEFF)
    if ($gradle -match 'buildStagingDirectory') { return }

    $staging = (Join-Path $Root $Name) -replace '\\', '/'
    New-Item -ItemType Directory -Path (Join-Path $Root $Name) -Force | Out-Null

    $block = @"
    externalNativeBuild {
        cmake {
            // Injected by deploy/android/03-build-apk.ps1: the object paths do
            // not fit under the project folder on Windows.
            buildStagingDirectory = file("$staging")
        }
    }
"@

    if ($gradle -notmatch '(?m)^android\s*\{') {
        throw "No android block in $GradlePath, so the build tree cannot be relocated."
    }

    $gradle = [regex]::Replace(
        $gradle, '(?m)^(android\s*\{)', ('$1' + "`n" + $block), 'None', [TimeSpan]::FromSeconds(5))

    Set-PlainTextFile -Path $GradlePath -Content $gradle
    Write-Host "  [ok]  C++ build tree moved to $staging" -ForegroundColor Gray
}

function Add-ShortObjectPaths {
    <#
        Windows will not take a path over 260 characters, and CMake builds an
        object file path by mirroring the whole absolute source path
        underneath the object directory. For react-native-gesture-handler that
        mirrored tail plus the CMakeFiles directories comes to 251 characters
        before any prefix at all, so the build cannot fit however short the
        project path is — moving the checkout to a drive root still leaves 305.

        CMAKE_OBJECT_PATH_MAX is the only lever that reaches it: over that
        length CMake replaces the mirrored directory with a short hash instead.
        Nothing else here is a workaround for ninja's limit, because ninja
        checks the name it is given and gives up; this changes the name.
    #>
    param([string] $GradlePath)

    $gradle = [System.IO.File]::ReadAllText($GradlePath).TrimStart([char] 0xFEFF)

    if ($gradle -match 'CMAKE_OBJECT_PATH_MAX') { return }

    if ($gradle -notmatch '(?s)defaultConfig\s*\{') {
        throw "No defaultConfig block in $GradlePath, so the CMake argument cannot be added."
    }

    $block = @'
        externalNativeBuild {
            cmake {
                // Injected by deploy/android/03-build-apk.ps1
                arguments "-DCMAKE_OBJECT_PATH_MAX=240"
            }
        }
'@

    $gradle = [regex]::Replace(
        $gradle, '(defaultConfig\s*\{)', ('$1' + "`n" + $block), 'None', [TimeSpan]::FromSeconds(5))

    Set-PlainTextFile -Path $GradlePath -Content $gradle
    Write-Host "  [ok]  CMake told to shorten object paths over 240 characters" -ForegroundColor Gray
}

function Remove-Tree {
    <#
        Gradle keeps handles on files under android/ for a moment after it
        exits, so a delete can fail — and the previous version swallowed that
        with -ErrorAction SilentlyContinue. The folder then survived into the
        next run carrying the file that had just failed to build, which is why
        the same error came back after it had been fixed.
    #>
    param([string] $Path, [switch] $Tolerate)

    if (-not (Test-Path $Path)) { return $true }

    for ($attempt = 1; $attempt -le 5; $attempt++) {
        try {
            Remove-Item $Path -Recurse -Force -ErrorAction Stop
            return $true
        }
        catch [System.IO.PathTooLongException] {
            # The native build writes paths past 260 characters, and
            # Remove-Item cannot then delete them — the folder it just built
            # becomes undeletable by the tool that asked for it. Robocopy uses
            # the wide API throughout, so mirroring an empty directory over the
            # top empties it whatever the names are.
            Write-Host "  Paths too long for Remove-Item; emptying with robocopy..." -ForegroundColor Gray
            $empty = Join-Path $env:TEMP ("empty-" + [Guid]::NewGuid().ToString('N').Substring(0, 8))
            New-Item -ItemType Directory -Path $empty -Force | Out-Null
            try {
                # 0-7 are success; 8 and above are real failures.
                Invoke-Native 'robocopy' 'robocopy' @(
                    $empty, $Path, '/MIR', '/NFL', '/NDL', '/NJH', '/NJS', '/NC', '/NS', '/R:1', '/W:1'
                ) -IgnoreExitCode | Out-Null
                if ($LASTEXITCODE -ge 8) { throw "robocopy exited $LASTEXITCODE" }
                Remove-Item $Path -Recurse -Force -ErrorAction Stop
                return $true
            }
            finally { Remove-Item $empty -Recurse -Force -ErrorAction SilentlyContinue }
        }
        catch {
            if ($attempt -eq 5) {
                if ($Tolerate) {
                    Write-Host ("  [warn] Could not remove {0}: {1}" -f $Path, $_.Exception.Message) -ForegroundColor Yellow
                    Write-Host "         It is rebuilt from scratch next run, so this is untidy rather than wrong." -ForegroundColor Gray
                    return $false
                }
                throw ("Could not remove $Path after 5 attempts: $($_.Exception.Message)`n" +
                    "Something is holding a file open — a Gradle daemon, an editor, or Explorer. " +
                    "Close it, or run: Get-Process java | Stop-Process")
            }
            Start-Sleep -Seconds 2
        }
    }
}

# --- Build -------------------------------------------------------------------

$built = @()

foreach ($name in $targets) {
    $spec = $apps[$name]
    $projectPath = Join-Path $SourcePath $spec.Dir
    if (-not (Test-Path $projectPath)) { throw "Not found: $projectPath. Check -SourcePath." }

    $signingProps = Join-Path $KeystoreDir "$name-signing.properties"
    if (-not (Test-Path $signingProps)) {
        throw "No signing key for $name. Run .\02-keystore.ps1 -App $name first."
    }

    Write-Host ("--- {0} ---" -f $spec.Label) -ForegroundColor Cyan

    $manifestBefore = $null

    Push-Location $projectPath
    try {
        # npm writes node_modules\.package-lock.json when an install finishes,
        # so its presence means "an install completed" and its timestamp means
        # "against this lock file". Testing only for the file was not enough: a
        # git pull that changes package-lock.json leaves the marker in place
        # and the build then runs against whatever was installed last time,
        # which is how a dependency fix gets pulled and then ignored.
        $installed = Join-Path $projectPath 'node_modules\.package-lock.json'
        $lockFile = Join-Path $projectPath 'package-lock.json'

        $needsInstall = -not (Test-Path $installed)
        if (-not $needsInstall -and (Test-Path $lockFile)) {
            $needsInstall = (Get-Item $lockFile).LastWriteTimeUtc -gt (Get-Item $installed).LastWriteTimeUtc
            if ($needsInstall) {
                Write-Host "  package-lock.json is newer than what is installed." -ForegroundColor Yellow
            }
        }

        if ($needsInstall) {
            Write-Host "  Installing dependencies..." -ForegroundColor Gray
            Invoke-Native "npm ci ($name)" 'npm' @('ci', '--no-audit', '--no-fund') -Stream
        }

        # These are read by app.config.js, which is what puts them into the
        # binary. Set for this process only.
        $env:CBMS_API_BASE_URL = $ApiBaseUrl
        $env:CBMS_ANDROID_VERSION_CODE = [string] $VersionCode
        $env:CBMS_SIGNING_PROPERTIES = $signingProps

        # Before prebuild as well as after. --clean is supposed to replace
        # android/, but a folder left behind by a failed run can survive it in
        # part, and then the build is against a mixture of two attempts. This
        # throws rather than continuing, because "mostly regenerated" is the
        # state that produces errors nobody can reproduce.
        Remove-Tree (Join-Path $projectPath 'android') | Out-Null

        # prebuild rewrites package.json - it normalises "main" and adds
        # scripts - and that leaves the checkout dirty. The next git pull then
        # refuses to touch the file, and every fix after this point silently
        # stops arriving on the server while the same error keeps coming back.
        # It cost three rounds of exactly that to notice. Restored in the
        # finally, so the build still gets whatever prebuild wanted.
        $manifestPath = Join-Path $projectPath 'package.json'
        $manifestBefore = [System.IO.File]::ReadAllBytes($manifestPath)

        Write-Host "  Generating the native project..." -ForegroundColor Gray
        Invoke-Native "expo prebuild ($name)" 'npx' @(
            'expo', 'prebuild', '--platform', 'android', '--clean', '--no-install') -Stream

        $androidPath = Join-Path $projectPath 'android'
        if (-not (Test-Path $androidPath)) { throw "expo prebuild produced no android/ folder." }

        # Gradle finds the SDK through this or through ANDROID_HOME; writing it
        # removes the difference between a shell that has the variable and a
        # service account that does not.
        # No BOM: java.util.Properties would read the mark as part of the first
        # key, so sdk.dir would become a key nobody looks up.
        Set-PlainTextFile -Path (Join-Path $androidPath 'local.properties') `
            -Content ("sdk.dir=" + ($sdk -replace '\\', '\\\\'))

        Add-ShortObjectPaths -GradlePath (Join-Path $androidPath 'app\build.gradle')
        Add-ShortBuildTree -GradlePath (Join-Path $androidPath 'app\build.gradle') -Root $NativeBuildRoot -Name $name
        Add-SigningConfig -GradlePath (Join-Path $androidPath 'app\build.gradle')
        Write-Host "  [ok]  Release signing configured" -ForegroundColor Green

        # Kept because a ten minute build that fails leaves nothing but
        # scrollback otherwise, and scrollback is finite, truncated when it is
        # pasted somewhere, and gone when the window closes. Several rounds of
        # this were spent not knowing what Gradle had actually said.
        $buildLog = Join-Path $OutputDir ("build-{0}.log" -f $name)

        Write-Host "  Gradle assembleRelease — the first run downloads Gradle and the SDK bits..." -ForegroundColor Gray
        Write-Host ("  Logging to {0}" -f $buildLog) -ForegroundColor Gray
        Push-Location $androidPath
        try {
            Invoke-Native "gradle assembleRelease ($name)" (Join-Path $androidPath 'gradlew.bat') @(
                'assembleRelease', '--no-daemon') -Stream -LogFile $buildLog
        }
        catch {
            # Gradle puts the useful part between "FAILURE:" and "* Try:", and
            # it has usually scrolled off by the time anyone looks. Repeat it
            # at the bottom where it will be read.
            if (Test-Path $buildLog) {
                $lines = Get-Content $buildLog
                $from = ($lines | Select-String -Pattern '^FAILURE:' | Select-Object -First 1).LineNumber
                if ($from) {
                    $to = ($lines | Select-Object -Skip $from | Select-String -Pattern '^\* Try:' |
                        Select-Object -First 1).LineNumber
                    $count = if ($to) { $to } else { 30 }
                    Write-Host "`n  What Gradle said:`n" -ForegroundColor Red
                    $lines | Select-Object -Skip ($from - 1) -First $count |
                        ForEach-Object { Write-Host ("    {0}" -f $_) -ForegroundColor Gray }
                    Write-Host ''
                }
            }
            throw
        }
        finally { Pop-Location }

        $apk = Join-Path $androidPath 'app\build\outputs\apk\release\app-release.apk'
        if (-not (Test-Path $apk)) { throw "Gradle reported success but there is no APK at $apk." }

        $stamp = Get-Date -Format 'yyyyMMdd'
        $target = Join-Path $OutputDir ("cbms-{0}-v{1}-{2}.apk" -f $name, $VersionCode, $stamp)
        Copy-Item $apk $target -Force

        $size = [Math]::Round((Get-Item $target).Length / 1MB, 1)
        Write-Host ("  [ok]  {0}  ({1} MB)" -f $target, $size) -ForegroundColor Green
        $built += $target
    }
    finally {
        Pop-Location
        Remove-Item Env:\CBMS_API_BASE_URL -ErrorAction SilentlyContinue
        Remove-Item Env:\CBMS_ANDROID_VERSION_CODE -ErrorAction SilentlyContinue
        Remove-Item Env:\CBMS_SIGNING_PROPERTIES -ErrorAction SilentlyContinue

        if ($manifestBefore) {
            $manifestNow = [System.IO.File]::ReadAllBytes($manifestPath)
            if ([Convert]::ToBase64String($manifestNow) -ne [Convert]::ToBase64String($manifestBefore)) {
                [System.IO.File]::WriteAllBytes($manifestPath, $manifestBefore)
                Write-Host "  [ok]  Restored package.json to how prebuild found it" -ForegroundColor Gray
            }
        }

        if (-not $KeepNativeProject) {
            # Regenerated every run, so leaving it behind only invites someone
            # to edit it and lose the change at the next build. Tolerated here
            # because this runs in a finally block, where throwing would hide
            # whatever sent us here — the next run removes it before prebuild
            # and does not tolerate a failure then.
            Remove-Tree (Join-Path $projectPath 'android') -Tolerate | Out-Null
        }
    }
}

# --- Report ------------------------------------------------------------------

Write-Host ("`nDone in {0:n0}s.`n" -f ((Get-Date) - $started).TotalSeconds) -ForegroundColor Green
foreach ($file in $built) { Write-Host ("  {0}" -f $file) -ForegroundColor White }

Write-Host "`nTo put one on a phone:" -ForegroundColor Cyan
Write-Host "  copy the file across and open it, allowing installation from this source; or" -ForegroundColor Gray
Write-Host "  with the phone plugged in and USB debugging on:" -ForegroundColor Gray
Write-Host ("    & `"{0}\platform-tools\adb.exe`" install -r `"<apk>`"" -f $sdk) -ForegroundColor Gray
Write-Host ""
Write-Host "These are signed with the CBMS release key, so a later build upgrades them" -ForegroundColor Gray
Write-Host "in place. Both apps talk to $ApiBaseUrl." -ForegroundColor Gray
Write-Host ""
