<#
.SYNOPSIS
    Builds a signed release APK for the applicant app, the coordinator app, or
    both.

.DESCRIPTION
    Runs entirely on this machine: no Expo account, no EAS, nothing uploaded.

    The API address is injected at build time rather than read from app.json.
    app.json holds the development default, which is localhost, and an APK
    built with that in it is a silent failure — it installs, it opens, and
    every request dies on the device with nothing on the server to show for it.

    The native project is regenerated from the Expo config on every run
    (`expo prebuild --clean`), so android/ is disposable and nothing built by
    hand survives to drift. The signing configuration is therefore re-applied
    each time, from the properties file 02-keystore.ps1 wrote.

.PARAMETER App
    applicant, coordinator, or both. Default both.

.PARAMETER ApiBaseUrl
    What the app talks to. Must be reachable from a phone on mobile data, which
    localhost and a private address are not.

.PARAMETER OutputDir
    Where the APKs are copied. Default E:\cbms-apk.

.EXAMPLE
    .\03-build-apk.ps1
    .\03-build-apk.ps1 -App coordinator -ApiBaseUrl https://leanstaging.qci.org.in/api
#>
[CmdletBinding()]
param(
    [ValidateSet('applicant', 'coordinator', 'both')]
    [string] $App = 'both',
    [string] $ApiBaseUrl = 'https://leanstaging.qci.org.in/api',
    [string] $SourcePath = 'E:\NDIE-Capacity-Building-main',
    [string] $OutputDir = 'E:\cbms-apk',
    [string] $KeystoreDir = 'E:\cbms-keystores',
    [int] $VersionCode = 0,
    [switch] $KeepNativeProject
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '..\windows\_common.ps1')

$started = Get-Date

# --- Sanity ------------------------------------------------------------------

if (-not $env:JAVA_HOME) { throw "JAVA_HOME is not set. Run .\01-prerequisites.ps1." }
$sdk = if ($env:ANDROID_HOME) { $env:ANDROID_HOME } else { $env:ANDROID_SDK_ROOT }
if (-not $sdk -or -not (Test-Path $sdk)) { throw "ANDROID_HOME is not set. Run .\01-prerequisites.ps1." }

# A phone is not on this machine's loopback and, on mobile data, not on its
# network either. Catching it here saves building an APK that cannot work.
if ($ApiBaseUrl -match 'localhost|127\.0\.0\.1|10\.0\.2\.2') {
    throw ("-ApiBaseUrl is $ApiBaseUrl, which no phone can reach. " +
        "Use the public address, e.g. https://leanstaging.qci.org.in/api")
}
if ($ApiBaseUrl -notmatch '/api/?$') {
    throw "-ApiBaseUrl should end in /api, e.g. https://leanstaging.qci.org.in/api"
}
if ($ApiBaseUrl -like 'http://*') {
    # Android has blocked cleartext by default since API 28, so this would not
    # merely be insecure - every request would fail.
    throw "-ApiBaseUrl must be https. Android blocks cleartext traffic by default."
}

$apps = @{
    applicant   = @{ Dir = 'mobile'; Label = 'CBMS Applicant' }
    coordinator = @{ Dir = 'mobile-coordinator'; Label = 'CBMS Coordinator' }
}
$targets = if ($App -eq 'both') { @('applicant', 'coordinator') } else { @($App) }

if (-not (Test-Path $OutputDir)) { New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null }

# --- The build number --------------------------------------------------------

# Android refuses to install an APK whose versionCode is not higher than the
# one already on the device, and the failure on the phone says only "app not
# installed". Kept here rather than in the repository so two builds of the same
# commit still differ.
$counterFile = Join-Path $OutputDir 'versioncode.txt'
if ($VersionCode -le 0) {
    $previous = 0
    if (Test-Path $counterFile) { [int]::TryParse((Get-Content $counterFile -Raw).Trim(), [ref] $previous) | Out-Null }
    $VersionCode = $previous + 1
}
Set-Content -Path $counterFile -Value $VersionCode -Encoding utf8

Write-Host "`nBuilding Android release APKs" -ForegroundColor Cyan
Write-Host ("  API          : {0}" -f $ApiBaseUrl) -ForegroundColor Gray
Write-Host ("  versionCode  : {0}" -f $VersionCode) -ForegroundColor Gray
Write-Host ("  output       : {0}`n" -f $OutputDir) -ForegroundColor Gray

# --- Signing -----------------------------------------------------------------

function Add-SigningConfig {
    <#
        The Expo template signs a release build with the debug key. That APK
        installs perfectly well, which is the problem: without this the script
        would hand back something that looks finished, cannot be published, and
        cannot be upgraded by a properly signed build later.

        The generated file is regenerated by every prebuild, so this is applied
        every run. It reads the password from a file whose path comes through
        the environment - nothing secret goes on a command line, where the
        process list would show it.
    #>
    param([string] $GradlePath)

    $gradle = Get-Content $GradlePath -Raw

    if ($gradle -notmatch '(?s)signingConfigs\s*\{') {
        throw "No signingConfigs block in $GradlePath. The Expo template has changed; this script needs updating rather than working around."
    }

    $release = @'
        release {
            // Injected by deploy/android/03-build-apk.ps1
            def cbmsProps = new Properties()
            def cbmsPath = System.getenv('CBMS_SIGNING_PROPERTIES')
            if (cbmsPath == null) {
                throw new GradleException('CBMS_SIGNING_PROPERTIES is not set.')
            }
            file(cbmsPath).withInputStream { cbmsProps.load(it) }
            storeFile file(cbmsProps['storeFile'])
            storePassword cbmsProps['storePassword']
            keyAlias cbmsProps['keyAlias']
            keyPassword cbmsProps['keyPassword']
        }
'@

    $gradle = [regex]::Replace(
        $gradle, '(signingConfigs\s*\{)', ('$1' + "`n" + $release), 'None', [TimeSpan]::FromSeconds(5))

    # Only the release buildType. The debug one keeps the debug key, which is
    # what makes a debug build installable alongside nothing in particular.
    $buildTypes = [regex]::Match($gradle, '(?s)buildTypes\s*\{.*')
    if (-not $buildTypes.Success) { throw "No buildTypes block in $GradlePath." }

    $patchedTail = [regex]::Replace(
        $buildTypes.Value,
        '(?s)(release\s*\{[^}]*?signingConfig\s+signingConfigs\.)debug',
        '${1}release', 'None', [TimeSpan]::FromSeconds(5))

    if ($patchedTail -eq $buildTypes.Value) {
        throw ("Could not point the release build at the release key in $GradlePath. " +
            "Refusing to carry on: the APK would be signed with the debug key and " +
            "could never be updated by a properly signed one.")
    }

    $gradle = $gradle.Substring(0, $buildTypes.Index) + $patchedTail
    Set-Content -Path $GradlePath -Value $gradle -Encoding utf8
}

# --- Build -------------------------------------------------------------------

$built = @()

foreach ($name in $targets) {
    $spec = $apps[$name]
    $projectPath = Join-Path $SourcePath $spec.Dir
    if (-not (Test-Path $projectPath)) { throw "Not found: $projectPath. Check -SourcePath." }

    $signingProps = Join-Path $KeystoreDir "$name-signing.properties"
    if (-not (Test-Path $signingProps)) {
        throw "No signing key for $name. Run .\02-keystore.ps1 -App $name first."
    }

    Write-Host ("--- {0} ---" -f $spec.Label) -ForegroundColor Cyan

    Push-Location $projectPath
    try {
        if (-not (Test-Path (Join-Path $projectPath 'node_modules\.package-lock.json'))) {
            Write-Host "  Installing dependencies (first run only)..." -ForegroundColor Gray
            Invoke-Native "npm ci ($name)" 'npm' @('ci', '--no-audit', '--no-fund') -Stream
        }

        # These are read by app.config.js, which is what puts them into the
        # binary. Set for this process only.
        $env:CBMS_API_BASE_URL = $ApiBaseUrl
        $env:CBMS_ANDROID_VERSION_CODE = [string] $VersionCode
        $env:CBMS_SIGNING_PROPERTIES = $signingProps

        Write-Host "  Generating the native project..." -ForegroundColor Gray
        Invoke-Native "expo prebuild ($name)" 'npx' @(
            'expo', 'prebuild', '--platform', 'android', '--clean', '--no-install') -Stream

        $androidPath = Join-Path $projectPath 'android'
        if (-not (Test-Path $androidPath)) { throw "expo prebuild produced no android/ folder." }

        # Gradle finds the SDK through this or through ANDROID_HOME; writing it
        # removes the difference between a shell that has the variable and a
        # service account that does not.
        Set-Content -Path (Join-Path $androidPath 'local.properties') `
            -Value ("sdk.dir=" + ($sdk -replace '\\', '\\\\')) -Encoding utf8

        Add-SigningConfig -GradlePath (Join-Path $androidPath 'app\build.gradle')
        Write-Host "  [ok]  Release signing configured" -ForegroundColor Green

        Write-Host "  Gradle assembleRelease — the first run downloads Gradle and the SDK bits..." -ForegroundColor Gray
        Push-Location $androidPath
        try {
            Invoke-Native "gradle assembleRelease ($name)" (Join-Path $androidPath 'gradlew.bat') @(
                'assembleRelease', '--no-daemon') -Stream
        }
        finally { Pop-Location }

        $apk = Join-Path $androidPath 'app\build\outputs\apk\release\app-release.apk'
        if (-not (Test-Path $apk)) { throw "Gradle reported success but there is no APK at $apk." }

        $stamp = Get-Date -Format 'yyyyMMdd'
        $target = Join-Path $OutputDir ("cbms-{0}-v{1}-{2}.apk" -f $name, $VersionCode, $stamp)
        Copy-Item $apk $target -Force

        $size = [Math]::Round((Get-Item $target).Length / 1MB, 1)
        Write-Host ("  [ok]  {0}  ({1} MB)" -f $target, $size) -ForegroundColor Green
        $built += $target
    }
    finally {
        Pop-Location
        Remove-Item Env:\CBMS_API_BASE_URL -ErrorAction SilentlyContinue
        Remove-Item Env:\CBMS_ANDROID_VERSION_CODE -ErrorAction SilentlyContinue
        Remove-Item Env:\CBMS_SIGNING_PROPERTIES -ErrorAction SilentlyContinue

        if (-not $KeepNativeProject) {
            # Regenerated every run, so leaving it behind only invites someone
            # to edit it and lose the change at the next build.
            Remove-Item (Join-Path $projectPath 'android') -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
}

# --- Report ------------------------------------------------------------------

Write-Host ("`nDone in {0:n0}s.`n" -f ((Get-Date) - $started).TotalSeconds) -ForegroundColor Green
foreach ($file in $built) { Write-Host ("  {0}" -f $file) -ForegroundColor White }

Write-Host "`nTo put one on a phone:" -ForegroundColor Cyan
Write-Host "  copy the file across and open it, allowing installation from this source; or" -ForegroundColor Gray
Write-Host "  with the phone plugged in and USB debugging on:" -ForegroundColor Gray
Write-Host ("    & `"{0}\platform-tools\adb.exe`" install -r `"<apk>`"" -f $sdk) -ForegroundColor Gray
Write-Host ""
Write-Host "These are signed with the CBMS release key, so a later build upgrades them" -ForegroundColor Gray
Write-Host "in place. Both apps talk to $ApiBaseUrl." -ForegroundColor Gray
Write-Host ""
