/**
 * State and district master sourced from the Local Government Directory (LGD),
 * Ministry of Panchayati Raj — the Government of India standard location
 * directory. Codes are LGD codes; names are reproduced as published.
 *
 * Source: https://lgdirectory.gov.in/  (36 states/UTs, 763 districts)
 */

export interface LgdState {
  /** LGD state code. */
  code: number;
  name: string;
  isUnionTerritory: boolean;
}

export interface LgdDistrict {
  /** LGD district code. */
  code: number;
  stateCode: number;
  name: string;
}

export const LGD_STATES: LgdState[] = [
  { code: 35, name: "ANDAMAN AND NICOBAR ISLANDS", isUnionTerritory: true },
  { code: 28, name: "ANDHRA PRADESH", isUnionTerritory: false },
  { code: 12, name: "ARUNACHAL PRADESH", isUnionTerritory: false },
  { code: 18, name: "ASSAM", isUnionTerritory: false },
  { code: 10, name: "BIHAR", isUnionTerritory: false },
  { code: 4, name: "CHANDIGARH", isUnionTerritory: true },
  { code: 22, name: "CHHATTISGARH", isUnionTerritory: false },
  { code: 7, name: "DELHI", isUnionTerritory: true },
  { code: 30, name: "GOA", isUnionTerritory: false },
  { code: 24, name: "GUJARAT", isUnionTerritory: false },
  { code: 6, name: "HARYANA", isUnionTerritory: false },
  { code: 2, name: "HIMACHAL PRADESH", isUnionTerritory: false },
  { code: 1, name: "JAMMU AND KASHMIR", isUnionTerritory: true },
  { code: 20, name: "JHARKHAND", isUnionTerritory: false },
  { code: 29, name: "KARNATAKA", isUnionTerritory: false },
  { code: 32, name: "KERALA", isUnionTerritory: false },
  { code: 37, name: "LADAKH", isUnionTerritory: true },
  { code: 31, name: "LAKSHADWEEP", isUnionTerritory: true },
  { code: 23, name: "MADHYA PRADESH", isUnionTerritory: false },
  { code: 27, name: "MAHARASHTRA", isUnionTerritory: false },
  { code: 14, name: "MANIPUR", isUnionTerritory: false },
  { code: 17, name: "MEGHALAYA", isUnionTerritory: false },
  { code: 15, name: "MIZORAM", isUnionTerritory: false },
  { code: 13, name: "NAGALAND", isUnionTerritory: false },
  { code: 21, name: "ODISHA", isUnionTerritory: false },
  { code: 34, name: "PUDUCHERRY", isUnionTerritory: true },
  { code: 3, name: "PUNJAB", isUnionTerritory: false },
  { code: 8, name: "RAJASTHAN", isUnionTerritory: false },
  { code: 11, name: "SIKKIM", isUnionTerritory: false },
  { code: 33, name: "TAMIL NADU", isUnionTerritory: false },
  { code: 36, name: "TELANGANA", isUnionTerritory: false },
  { code: 38, name: "THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU", isUnionTerritory: true },
  { code: 16, name: "TRIPURA", isUnionTerritory: false },
  { code: 9, name: "UTTAR PRADESH", isUnionTerritory: false },
  { code: 5, name: "UTTARAKHAND", isUnionTerritory: false },
  { code: 19, name: "WEST BENGAL", isUnionTerritory: false },
];

export const LGD_DISTRICTS: LgdDistrict[] = [
  { code: 1, stateCode: 1, name: "ANANTNAG" },
  { code: 623, stateCode: 1, name: "BANDIPORA" },
  { code: 3, stateCode: 1, name: "BARAMULLA" },
  { code: 2, stateCode: 1, name: "Budgam" },
  { code: 4, stateCode: 1, name: "DODA" },
  { code: 626, stateCode: 1, name: "GANDERBAL" },
  { code: 5, stateCode: 1, name: "JAMMU" },
  { code: 7, stateCode: 1, name: "KATHUA" },
  { code: 620, stateCode: 1, name: "KISHTWAR" },
  { code: 622, stateCode: 1, name: "KULGAM" },
  { code: 8, stateCode: 1, name: "KUPWARA" },
  { code: 10, stateCode: 1, name: "POONCH" },
  { code: 11, stateCode: 1, name: "PULWAMA" },
  { code: 12, stateCode: 1, name: "RAJOURI" },
  { code: 621, stateCode: 1, name: "RAMBAN" },
  { code: 627, stateCode: 1, name: "REASI" },
  { code: 624, stateCode: 1, name: "SAMBA" },
  { code: 625, stateCode: 1, name: "SHOPIAN" },
  { code: 13, stateCode: 1, name: "SRINAGAR" },
  { code: 14, stateCode: 1, name: "UDHAMPUR" },
  { code: 15, stateCode: 2, name: "BILASPUR" },
  { code: 16, stateCode: 2, name: "CHAMBA" },
  { code: 17, stateCode: 2, name: "HAMIRPUR" },
  { code: 18, stateCode: 2, name: "KANGRA" },
  { code: 19, stateCode: 2, name: "KINNAUR" },
  { code: 20, stateCode: 2, name: "KULLU" },
  { code: 21, stateCode: 2, name: "LAHUL AND SPITI" },
  { code: 22, stateCode: 2, name: "MANDI" },
  { code: 23, stateCode: 2, name: "SHIMLA" },
  { code: 24, stateCode: 2, name: "SIRMAUR" },
  { code: 25, stateCode: 2, name: "SOLAN" },
  { code: 26, stateCode: 2, name: "UNA" },
  { code: 27, stateCode: 3, name: "AMRITSAR" },
  { code: 605, stateCode: 3, name: "BARNALA" },
  { code: 28, stateCode: 3, name: "BATHINDA" },
  { code: 29, stateCode: 3, name: "FARIDKOT" },
  { code: 30, stateCode: 3, name: "FATEHGARH SAHIB" },
  { code: 651, stateCode: 3, name: "FAZILKA" },
  { code: 31, stateCode: 3, name: "FEROZEPUR" },
  { code: 32, stateCode: 3, name: "GURDASPUR" },
  { code: 33, stateCode: 3, name: "HOSHIARPUR" },
  { code: 34, stateCode: 3, name: "JALANDHAR" },
  { code: 35, stateCode: 3, name: "KAPURTHALA" },
  { code: 36, stateCode: 3, name: "LUDHIANA" },
  { code: 737, stateCode: 3, name: "MALERKOTLA" },
  { code: 37, stateCode: 3, name: "MANSA" },
  { code: 38, stateCode: 3, name: "MOGA" },
  { code: 662, stateCode: 3, name: "PATHANKOT" },
  { code: 41, stateCode: 3, name: "PATIALA" },
  { code: 42, stateCode: 3, name: "RUPNAGAR" },
  { code: 608, stateCode: 3, name: "S.A.S Nagar" },
  { code: 43, stateCode: 3, name: "SANGRUR" },
  { code: 40, stateCode: 3, name: "Shahid Bhagat Singh Nagar" },
  { code: 39, stateCode: 3, name: "SRI MUKTSAR SAHIB" },
  { code: 609, stateCode: 3, name: "Tarn Taran" },
  { code: 44, stateCode: 4, name: "CHANDIGARH" },
  { code: 45, stateCode: 5, name: "ALMORA" },
  { code: 46, stateCode: 5, name: "BAGESHWAR" },
  { code: 47, stateCode: 5, name: "CHAMOLI" },
  { code: 48, stateCode: 5, name: "CHAMPAWAT" },
  { code: 49, stateCode: 5, name: "DEHRADUN" },
  { code: 50, stateCode: 5, name: "HARIDWAR" },
  { code: 51, stateCode: 5, name: "NAINITAL" },
  { code: 52, stateCode: 5, name: "PAURI GARHWAL" },
  { code: 53, stateCode: 5, name: "PITHORAGARH" },
  { code: 54, stateCode: 5, name: "RUDRA PRAYAG" },
  { code: 55, stateCode: 5, name: "TEHRI GARHWAL" },
  { code: 56, stateCode: 5, name: "UDAM SINGH NAGAR" },
  { code: 57, stateCode: 5, name: "UTTAR KASHI" },
  { code: 58, stateCode: 6, name: "AMBALA" },
  { code: 59, stateCode: 6, name: "BHIWANI" },
  { code: 701, stateCode: 6, name: "CHARKI DADRI" },
  { code: 60, stateCode: 6, name: "FARIDABAD" },
  { code: 61, stateCode: 6, name: "FATEHABAD" },
  { code: 62, stateCode: 6, name: "GURUGRAM" },
  { code: 63, stateCode: 6, name: "HISAR" },
  { code: 64, stateCode: 6, name: "JHAJJAR" },
  { code: 65, stateCode: 6, name: "JIND" },
  { code: 66, stateCode: 6, name: "KAITHAL" },
  { code: 67, stateCode: 6, name: "KARNAL" },
  { code: 68, stateCode: 6, name: "KURUKSHETRA" },
  { code: 69, stateCode: 6, name: "MAHENDRAGARH" },
  { code: 604, stateCode: 6, name: "NUH" },
  { code: 619, stateCode: 6, name: "PALWAL" },
  { code: 70, stateCode: 6, name: "PANCHKULA" },
  { code: 71, stateCode: 6, name: "PANIPAT" },
  { code: 72, stateCode: 6, name: "REWARI" },
  { code: 73, stateCode: 6, name: "ROHTAK" },
  { code: 74, stateCode: 6, name: "SIRSA" },
  { code: 75, stateCode: 6, name: "SONIPAT" },
  { code: 76, stateCode: 6, name: "YAMUNANAGAR" },
  { code: 77, stateCode: 7, name: "CENTRAL" },
  { code: 78, stateCode: 7, name: "EAST" },
  { code: 79, stateCode: 7, name: "NEW DELHI" },
  { code: 80, stateCode: 7, name: "NORTH" },
  { code: 81, stateCode: 7, name: "NORTH EAST" },
  { code: 82, stateCode: 7, name: "NORTH WEST" },
  { code: 671, stateCode: 7, name: "SHAHDARA" },
  { code: 83, stateCode: 7, name: "SOUTH" },
  { code: 670, stateCode: 7, name: "South East" },
  { code: 84, stateCode: 7, name: "SOUTH WEST" },
  { code: 85, stateCode: 7, name: "WEST" },
  { code: 86, stateCode: 8, name: "AJMER" },
  { code: 87, stateCode: 8, name: "ALWAR" },
  { code: 88, stateCode: 8, name: "BANSWARA" },
  { code: 89, stateCode: 8, name: "BARAN" },
  { code: 90, stateCode: 8, name: "BARMER" },
  { code: 91, stateCode: 8, name: "BHARATPUR" },
  { code: 92, stateCode: 8, name: "BHILWARA" },
  { code: 93, stateCode: 8, name: "BIKANER" },
  { code: 94, stateCode: 8, name: "BUNDI" },
  { code: 95, stateCode: 8, name: "CHITTORGARH" },
  { code: 96, stateCode: 8, name: "CHURU" },
  { code: 97, stateCode: 8, name: "DAUSA" },
  { code: 98, stateCode: 8, name: "DHOLPUR" },
  { code: 99, stateCode: 8, name: "DUNGARPUR" },
  { code: 100, stateCode: 8, name: "GANGANAGAR" },
  { code: 101, stateCode: 8, name: "HANUMANGARH" },
  { code: 102, stateCode: 8, name: "JAIPUR" },
  { code: 103, stateCode: 8, name: "JAISALMER" },
  { code: 104, stateCode: 8, name: "JALORE" },
  { code: 105, stateCode: 8, name: "JHALAWAR" },
  { code: 106, stateCode: 8, name: "JHUNJHUNU" },
  { code: 107, stateCode: 8, name: "JODHPUR" },
  { code: 108, stateCode: 8, name: "KARAULI" },
  { code: 109, stateCode: 8, name: "KOTA" },
  { code: 110, stateCode: 8, name: "NAGAUR" },
  { code: 111, stateCode: 8, name: "PALI" },
  { code: 629, stateCode: 8, name: "PRATAPGARH" },
  { code: 112, stateCode: 8, name: "RAJSAMAND" },
  { code: 113, stateCode: 8, name: "SAWAI MADHOPUR" },
  { code: 114, stateCode: 8, name: "SIKAR" },
  { code: 115, stateCode: 8, name: "SIROHI" },
  { code: 116, stateCode: 8, name: "TONK" },
  { code: 117, stateCode: 8, name: "UDAIPUR" },
  { code: 118, stateCode: 9, name: "AGRA" },
  { code: 119, stateCode: 9, name: "ALIGARH" },
  { code: 121, stateCode: 9, name: "AMBEDKAR NAGAR" },
  { code: 640, stateCode: 9, name: "Amethi" },
  { code: 154, stateCode: 9, name: "AMROHA" },
  { code: 122, stateCode: 9, name: "AURAIYA" },
  { code: 140, stateCode: 9, name: "AYODHYA" },
  { code: 123, stateCode: 9, name: "AZAMGARH" },
  { code: 124, stateCode: 9, name: "BAGHPAT" },
  { code: 125, stateCode: 9, name: "BAHRAICH" },
  { code: 126, stateCode: 9, name: "BALLIA" },
  { code: 127, stateCode: 9, name: "BALRAMPUR" },
  { code: 128, stateCode: 9, name: "BANDA" },
  { code: 129, stateCode: 9, name: "BARABANKI" },
  { code: 130, stateCode: 9, name: "BAREILLY" },
  { code: 131, stateCode: 9, name: "BASTI" },
  { code: 179, stateCode: 9, name: "BHADOHI" },
  { code: 132, stateCode: 9, name: "BIJNOR" },
  { code: 133, stateCode: 9, name: "BUDAUN" },
  { code: 134, stateCode: 9, name: "BULANDSHAHR" },
  { code: 135, stateCode: 9, name: "CHANDAULI" },
  { code: 136, stateCode: 9, name: "CHITRAKOOT" },
  { code: 137, stateCode: 9, name: "DEORIA" },
  { code: 138, stateCode: 9, name: "ETAH" },
  { code: 139, stateCode: 9, name: "ETAWAH" },
  { code: 141, stateCode: 9, name: "FARRUKHABAD" },
  { code: 142, stateCode: 9, name: "FATEHPUR" },
  { code: 143, stateCode: 9, name: "FIROZABAD" },
  { code: 144, stateCode: 9, name: "GAUTAM BUDDHA NAGAR" },
  { code: 145, stateCode: 9, name: "GHAZIABAD" },
  { code: 146, stateCode: 9, name: "GHAZIPUR" },
  { code: 147, stateCode: 9, name: "GONDA" },
  { code: 148, stateCode: 9, name: "GORAKHPUR" },
  { code: 149, stateCode: 9, name: "HAMIRPUR" },
  { code: 661, stateCode: 9, name: "HAPUR" },
  { code: 150, stateCode: 9, name: "HARDOI" },
  { code: 163, stateCode: 9, name: "HATHRAS" },
  { code: 151, stateCode: 9, name: "JALAUN" },
  { code: 152, stateCode: 9, name: "JAUNPUR" },
  { code: 153, stateCode: 9, name: "JHANSI" },
  { code: 155, stateCode: 9, name: "KANNAUJ" },
  { code: 156, stateCode: 9, name: "KANPUR DEHAT" },
  { code: 157, stateCode: 9, name: "KANPUR NAGAR" },
  { code: 633, stateCode: 9, name: "Kasganj" },
  { code: 158, stateCode: 9, name: "KAUSHAMBI" },
  { code: 159, stateCode: 9, name: "KHERI" },
  { code: 160, stateCode: 9, name: "KUSHI NAGAR" },
  { code: 161, stateCode: 9, name: "LALITPUR" },
  { code: 162, stateCode: 9, name: "LUCKNOW" },
  { code: 164, stateCode: 9, name: "MAHARAJGANJ" },
  { code: 165, stateCode: 9, name: "MAHOBA" },
  { code: 166, stateCode: 9, name: "MAINPURI" },
  { code: 167, stateCode: 9, name: "MATHURA" },
  { code: 168, stateCode: 9, name: "MAU" },
  { code: 169, stateCode: 9, name: "MEERUT" },
  { code: 170, stateCode: 9, name: "MIRZAPUR" },
  { code: 171, stateCode: 9, name: "MORADABAD" },
  { code: 172, stateCode: 9, name: "MUZAFFARNAGAR" },
  { code: 173, stateCode: 9, name: "PILIBHIT" },
  { code: 174, stateCode: 9, name: "PRATAPGARH" },
  { code: 120, stateCode: 9, name: "PRAYAGRAJ" },
  { code: 175, stateCode: 9, name: "RAE BARELI" },
  { code: 176, stateCode: 9, name: "RAMPUR" },
  { code: 177, stateCode: 9, name: "SAHARANPUR" },
  { code: 659, stateCode: 9, name: "SAMBHAL" },
  { code: 178, stateCode: 9, name: "SANT KABEER NAGAR" },
  { code: 180, stateCode: 9, name: "SHAHJAHANPUR" },
  { code: 660, stateCode: 9, name: "SHAMLI" },
  { code: 181, stateCode: 9, name: "SHRAVASTI" },
  { code: 182, stateCode: 9, name: "SIDDHARTH NAGAR" },
  { code: 183, stateCode: 9, name: "SITAPUR" },
  { code: 184, stateCode: 9, name: "SONBHADRA" },
  { code: 185, stateCode: 9, name: "SULTANPUR" },
  { code: 186, stateCode: 9, name: "UNNAO" },
  { code: 187, stateCode: 9, name: "VARANASI" },
  { code: 188, stateCode: 10, name: "ARARIA" },
  { code: 611, stateCode: 10, name: "ARWAL" },
  { code: 189, stateCode: 10, name: "AURANGABAD" },
  { code: 190, stateCode: 10, name: "BANKA" },
  { code: 191, stateCode: 10, name: "BEGUSARAI" },
  { code: 192, stateCode: 10, name: "BHAGALPUR" },
  { code: 193, stateCode: 10, name: "BHOJPUR" },
  { code: 194, stateCode: 10, name: "BUXAR" },
  { code: 195, stateCode: 10, name: "DARBHANGA" },
  { code: 196, stateCode: 10, name: "GAYA" },
  { code: 197, stateCode: 10, name: "GOPALGANJ" },
  { code: 198, stateCode: 10, name: "JAMUI" },
  { code: 199, stateCode: 10, name: "JEHANABAD" },
  { code: 200, stateCode: 10, name: "KAIMUR (BHABUA)" },
  { code: 201, stateCode: 10, name: "KATIHAR" },
  { code: 202, stateCode: 10, name: "KHAGARIA" },
  { code: 203, stateCode: 10, name: "KISHANGANJ" },
  { code: 204, stateCode: 10, name: "LAKHISARAI" },
  { code: 205, stateCode: 10, name: "MADHEPURA" },
  { code: 206, stateCode: 10, name: "MADHUBANI" },
  { code: 207, stateCode: 10, name: "MUNGER" },
  { code: 208, stateCode: 10, name: "MUZAFFARPUR" },
  { code: 209, stateCode: 10, name: "NALANDA" },
  { code: 210, stateCode: 10, name: "NAWADA" },
  { code: 211, stateCode: 10, name: "PASHCHIM CHAMPARAN" },
  { code: 212, stateCode: 10, name: "PATNA" },
  { code: 213, stateCode: 10, name: "PURBI CHAMPARAN" },
  { code: 214, stateCode: 10, name: "PURNIA" },
  { code: 215, stateCode: 10, name: "ROHTAS" },
  { code: 216, stateCode: 10, name: "SAHARSA" },
  { code: 217, stateCode: 10, name: "SAMASTIPUR" },
  { code: 218, stateCode: 10, name: "SARAN" },
  { code: 219, stateCode: 10, name: "SHEIKHPURA" },
  { code: 220, stateCode: 10, name: "SHEOHAR" },
  { code: 221, stateCode: 10, name: "SITAMARHI" },
  { code: 222, stateCode: 10, name: "SIWAN" },
  { code: 223, stateCode: 10, name: "SUPAUL" },
  { code: 224, stateCode: 10, name: "VAISHALI" },
  { code: 225, stateCode: 11, name: "Gangtok" },
  { code: 228, stateCode: 11, name: "Gyalshing" },
  { code: 226, stateCode: 11, name: "Mangan" },
  { code: 227, stateCode: 11, name: "Namchi" },
  { code: 741, stateCode: 11, name: "Pakyong" },
  { code: 742, stateCode: 11, name: "Soreng" },
  { code: 628, stateCode: 12, name: "ANJAW" },
  { code: 229, stateCode: 12, name: "CHANGLANG" },
  { code: 230, stateCode: 12, name: "DIBANG VALLEY" },
  { code: 231, stateCode: 12, name: "EAST KAMENG" },
  { code: 232, stateCode: 12, name: "EAST SIANG" },
  { code: 718, stateCode: 12, name: "KAMLE" },
  { code: 677, stateCode: 12, name: "KRA DAADI" },
  { code: 233, stateCode: 12, name: "KURUNG KUMEY" },
  { code: 724, stateCode: 12, name: "LEPARADA" },
  { code: 234, stateCode: 12, name: "LOHIT" },
  { code: 666, stateCode: 12, name: "LONGDING" },
  { code: 235, stateCode: 12, name: "LOWER DIBANG VALLEY" },
  { code: 719, stateCode: 12, name: "LOWER SIANG" },
  { code: 236, stateCode: 12, name: "LOWER SUBANSIRI" },
  { code: 678, stateCode: 12, name: "NAMSAI" },
  { code: 723, stateCode: 12, name: "PAKKE KESSANG" },
  { code: 237, stateCode: 12, name: "PAPUM PARE" },
  { code: 725, stateCode: 12, name: "SHI YOMI" },
  { code: 679, stateCode: 12, name: "SIANG" },
  { code: 238, stateCode: 12, name: "TAWANG" },
  { code: 239, stateCode: 12, name: "TIRAP" },
  { code: 240, stateCode: 12, name: "UPPER SIANG" },
  { code: 241, stateCode: 12, name: "UPPER SUBANSIRI" },
  { code: 242, stateCode: 12, name: "WEST KAMENG" },
  { code: 243, stateCode: 12, name: "WEST SIANG" },
  { code: 758, stateCode: 13, name: "Chumoukedima" },
  { code: 244, stateCode: 13, name: "DIMAPUR" },
  { code: 614, stateCode: 13, name: "KIPHIRE" },
  { code: 245, stateCode: 13, name: "KOHIMA" },
  { code: 615, stateCode: 13, name: "LONGLENG" },
  { code: 246, stateCode: 13, name: "MOKOKCHUNG" },
  { code: 247, stateCode: 13, name: "MON" },
  { code: 736, stateCode: 13, name: "Noklak" },
  { code: 613, stateCode: 13, name: "PEREN" },
  { code: 248, stateCode: 13, name: "PHEK" },
  { code: 757, stateCode: 13, name: "Tseminyu" },
  { code: 249, stateCode: 13, name: "TUENSANG" },
  { code: 250, stateCode: 13, name: "WOKHA" },
  { code: 251, stateCode: 13, name: "ZUNHEBOTO" },
  { code: 252, stateCode: 14, name: "BISHNUPUR" },
  { code: 253, stateCode: 14, name: "CHANDEL" },
  { code: 254, stateCode: 14, name: "CHURACHANDPUR" },
  { code: 255, stateCode: 14, name: "IMPHAL EAST" },
  { code: 256, stateCode: 14, name: "IMPHAL WEST" },
  { code: 713, stateCode: 14, name: "JIRIBAM" },
  { code: 711, stateCode: 14, name: "KAKCHING" },
  { code: 717, stateCode: 14, name: "KAMJONG" },
  { code: 712, stateCode: 14, name: "KANGPOKPI" },
  { code: 714, stateCode: 14, name: "NONEY" },
  { code: 715, stateCode: 14, name: "PHERZAWL" },
  { code: 257, stateCode: 14, name: "SENAPATI" },
  { code: 258, stateCode: 14, name: "TAMENGLONG" },
  { code: 716, stateCode: 14, name: "TENGNOUPAL" },
  { code: 259, stateCode: 14, name: "THOUBAL" },
  { code: 260, stateCode: 14, name: "UKHRUL" },
  { code: 261, stateCode: 15, name: "AIZAWL" },
  { code: 262, stateCode: 15, name: "CHAMPHAI" },
  { code: 726, stateCode: 15, name: "Hnahthial" },
  { code: 728, stateCode: 15, name: "KHAWZAWL" },
  { code: 263, stateCode: 15, name: "KOLASIB" },
  { code: 264, stateCode: 15, name: "LAWNGTLAI" },
  { code: 265, stateCode: 15, name: "LUNGLEI" },
  { code: 266, stateCode: 15, name: "MAMIT" },
  { code: 267, stateCode: 15, name: "SAIHA" },
  { code: 727, stateCode: 15, name: "SAITUAL" },
  { code: 268, stateCode: 15, name: "SERCHHIP" },
  { code: 269, stateCode: 16, name: "Dhalai" },
  { code: 654, stateCode: 16, name: "Gomati" },
  { code: 652, stateCode: 16, name: "Khowai" },
  { code: 270, stateCode: 16, name: "North Tripura" },
  { code: 653, stateCode: 16, name: "Sepahijala" },
  { code: 271, stateCode: 16, name: "South Tripura" },
  { code: 655, stateCode: 16, name: "Unakoti" },
  { code: 272, stateCode: 16, name: "West Tripura" },
  { code: 273, stateCode: 17, name: "EAST GARO HILLS" },
  { code: 657, stateCode: 17, name: "EAST JAINTIA HILLS" },
  { code: 274, stateCode: 17, name: "EAST KHASI HILLS" },
  { code: 740, stateCode: 17, name: "EASTERN WEST KHASI HILLS" },
  { code: 656, stateCode: 17, name: "NORTH GARO HILLS" },
  { code: 276, stateCode: 17, name: "RI BHOI" },
  { code: 277, stateCode: 17, name: "SOUTH GARO HILLS" },
  { code: 663, stateCode: 17, name: "SOUTH WEST GARO HILLS" },
  { code: 658, stateCode: 17, name: "SOUTH WEST KHASI HILLS" },
  { code: 278, stateCode: 17, name: "WEST GARO HILLS" },
  { code: 275, stateCode: 17, name: "WEST JAINTIA HILLS" },
  { code: 279, stateCode: 17, name: "WEST KHASI HILLS" },
  { code: 739, stateCode: 18, name: "BAJALI" },
  { code: 616, stateCode: 18, name: "BAKSA" },
  { code: 280, stateCode: 18, name: "BARPETA" },
  { code: 705, stateCode: 18, name: "Biswanath" },
  { code: 281, stateCode: 18, name: "BONGAIGAON" },
  { code: 282, stateCode: 18, name: "CACHAR" },
  { code: 708, stateCode: 18, name: "CHARAIDEO" },
  { code: 612, stateCode: 18, name: "CHIRANG" },
  { code: 283, stateCode: 18, name: "DARRANG" },
  { code: 284, stateCode: 18, name: "DHEMAJI" },
  { code: 285, stateCode: 18, name: "DHUBRI" },
  { code: 286, stateCode: 18, name: "DIBRUGARH" },
  { code: 299, stateCode: 18, name: "DIMA HASAO" },
  { code: 287, stateCode: 18, name: "GOALPARA" },
  { code: 288, stateCode: 18, name: "GOLAGHAT" },
  { code: 289, stateCode: 18, name: "HAILAKANDI" },
  { code: 709, stateCode: 18, name: "HOJAI" },
  { code: 290, stateCode: 18, name: "JORHAT" },
  { code: 291, stateCode: 18, name: "KAMRUP" },
  { code: 618, stateCode: 18, name: "KAMRUP METRO" },
  { code: 292, stateCode: 18, name: "KARBI ANGLONG" },
  { code: 293, stateCode: 18, name: "KARIMGANJ" },
  { code: 294, stateCode: 18, name: "KOKRAJHAR" },
  { code: 295, stateCode: 18, name: "LAKHIMPUR" },
  { code: 706, stateCode: 18, name: "MAJULI" },
  { code: 296, stateCode: 18, name: "MARIGAON" },
  { code: 297, stateCode: 18, name: "NAGAON" },
  { code: 298, stateCode: 18, name: "NALBARI" },
  { code: 300, stateCode: 18, name: "SIVASAGAR" },
  { code: 301, stateCode: 18, name: "SONITPUR" },
  { code: 707, stateCode: 18, name: "SOUTH SALMARA MANCACHAR" },
  { code: 756, stateCode: 18, name: "TAMULPUR" },
  { code: 302, stateCode: 18, name: "TINSUKIA" },
  { code: 617, stateCode: 18, name: "UDALGURI" },
  { code: 710, stateCode: 18, name: "WEST KARBI ANGLONG" },
  { code: 303, stateCode: 19, name: "24 PARAGANAS NORTH" },
  { code: 304, stateCode: 19, name: "24 PARAGANAS SOUTH" },
  { code: 664, stateCode: 19, name: "Alipurduar" },
  { code: 305, stateCode: 19, name: "BANKURA" },
  { code: 307, stateCode: 19, name: "BIRBHUM" },
  { code: 308, stateCode: 19, name: "COOCHBEHAR" },
  { code: 309, stateCode: 19, name: "DARJEELING" },
  { code: 310, stateCode: 19, name: "DINAJPUR DAKSHIN" },
  { code: 311, stateCode: 19, name: "DINAJPUR UTTAR" },
  { code: 312, stateCode: 19, name: "HOOGHLY" },
  { code: 313, stateCode: 19, name: "HOWRAH" },
  { code: 314, stateCode: 19, name: "JALPAIGURI" },
  { code: 703, stateCode: 19, name: "Jhargram" },
  { code: 702, stateCode: 19, name: "KALIMPONG" },
  { code: 315, stateCode: 19, name: "KOLKATA" },
  { code: 316, stateCode: 19, name: "MALDAH" },
  { code: 317, stateCode: 19, name: "MEDINIPUR EAST" },
  { code: 318, stateCode: 19, name: "MEDINIPUR WEST" },
  { code: 319, stateCode: 19, name: "MURSHIDABAD" },
  { code: 320, stateCode: 19, name: "NADIA" },
  { code: 704, stateCode: 19, name: "PASCHIM BARDHAMAN" },
  { code: 306, stateCode: 19, name: "PURBA BARDHAMAN" },
  { code: 321, stateCode: 19, name: "PURULIA" },
  { code: 322, stateCode: 20, name: "BOKARO" },
  { code: 323, stateCode: 20, name: "CHATRA" },
  { code: 324, stateCode: 20, name: "DEOGHAR" },
  { code: 325, stateCode: 20, name: "DHANBAD" },
  { code: 326, stateCode: 20, name: "DUMKA" },
  { code: 327, stateCode: 20, name: "EAST SINGHBUM" },
  { code: 328, stateCode: 20, name: "GARHWA" },
  { code: 329, stateCode: 20, name: "GIRIDIH" },
  { code: 330, stateCode: 20, name: "GODDA" },
  { code: 331, stateCode: 20, name: "GUMLA" },
  { code: 332, stateCode: 20, name: "HAZARIBAGH" },
  { code: 333, stateCode: 20, name: "JAMTARA" },
  { code: 606, stateCode: 20, name: "KHUNTI" },
  { code: 334, stateCode: 20, name: "KODERMA" },
  { code: 335, stateCode: 20, name: "LATEHAR" },
  { code: 336, stateCode: 20, name: "LOHARDAGA" },
  { code: 337, stateCode: 20, name: "PAKUR" },
  { code: 338, stateCode: 20, name: "PALAMU" },
  { code: 607, stateCode: 20, name: "RAMGARH" },
  { code: 339, stateCode: 20, name: "RANCHI" },
  { code: 340, stateCode: 20, name: "SAHEBGANJ" },
  { code: 341, stateCode: 20, name: "SARAIKELA KHARSAWAN" },
  { code: 342, stateCode: 20, name: "SIMDEGA" },
  { code: 343, stateCode: 20, name: "WEST SINGHBHUM" },
  { code: 344, stateCode: 21, name: "ANUGUL" },
  { code: 345, stateCode: 21, name: "BALANGIR" },
  { code: 346, stateCode: 21, name: "BALESHWAR" },
  { code: 347, stateCode: 21, name: "BARGARH" },
  { code: 348, stateCode: 21, name: "BHADRAK" },
  { code: 349, stateCode: 21, name: "BOUDH" },
  { code: 350, stateCode: 21, name: "CUTTACK" },
  { code: 351, stateCode: 21, name: "DEOGARH" },
  { code: 352, stateCode: 21, name: "DHENKANAL" },
  { code: 353, stateCode: 21, name: "GAJAPATI" },
  { code: 354, stateCode: 21, name: "GANJAM" },
  { code: 355, stateCode: 21, name: "JAGATSINGHAPUR" },
  { code: 356, stateCode: 21, name: "JAJAPUR" },
  { code: 357, stateCode: 21, name: "JHARSUGUDA" },
  { code: 358, stateCode: 21, name: "KALAHANDI" },
  { code: 359, stateCode: 21, name: "KANDHAMAL" },
  { code: 360, stateCode: 21, name: "KENDRAPARA" },
  { code: 361, stateCode: 21, name: "KENDUJHAR" },
  { code: 362, stateCode: 21, name: "KHORDHA" },
  { code: 363, stateCode: 21, name: "KORAPUT" },
  { code: 364, stateCode: 21, name: "MALKANGIRI" },
  { code: 365, stateCode: 21, name: "MAYURBHANJ" },
  { code: 366, stateCode: 21, name: "NABARANGPUR" },
  { code: 367, stateCode: 21, name: "NAYAGARH" },
  { code: 368, stateCode: 21, name: "NUAPADA" },
  { code: 369, stateCode: 21, name: "PURI" },
  { code: 370, stateCode: 21, name: "RAYAGADA" },
  { code: 371, stateCode: 21, name: "SAMBALPUR" },
  { code: 372, stateCode: 21, name: "SONEPUR" },
  { code: 373, stateCode: 21, name: "SUNDARGARH" },
  { code: 646, stateCode: 22, name: "BALOD" },
  { code: 644, stateCode: 22, name: "BALODA BAZAR" },
  { code: 649, stateCode: 22, name: "BALRAMPUR" },
  { code: 374, stateCode: 22, name: "BASTAR" },
  { code: 650, stateCode: 22, name: "BEMETARA" },
  { code: 636, stateCode: 22, name: "BIJAPUR" },
  { code: 375, stateCode: 22, name: "BILASPUR" },
  { code: 376, stateCode: 22, name: "DANTEWADA" },
  { code: 377, stateCode: 22, name: "DHAMTARI" },
  { code: 378, stateCode: 22, name: "DURG" },
  { code: 645, stateCode: 22, name: "GARIYABAND" },
  { code: 734, stateCode: 22, name: "Gaurella Pendra Marwahi" },
  { code: 379, stateCode: 22, name: "JANJGIR-CHAMPA" },
  { code: 380, stateCode: 22, name: "JASHPUR" },
  { code: 382, stateCode: 22, name: "KABIRDHAM" },
  { code: 381, stateCode: 22, name: "KANKER" },
  { code: 759, stateCode: 22, name: "KHAIRGARH CHHUIKHADAN GANDAI" },
  { code: 643, stateCode: 22, name: "KONDAGAON" },
  { code: 383, stateCode: 22, name: "KORBA" },
  { code: 384, stateCode: 22, name: "KOREA" },
  { code: 385, stateCode: 22, name: "MAHASAMUND" },
  { code: 760, stateCode: 22, name: "MANENDRAGARH CHIRIMIRI BHARATPUR" },
  { code: 761, stateCode: 22, name: "MOHLA MANPUR AMBAGARH CHOUKI" },
  { code: 647, stateCode: 22, name: "MUNGELI" },
  { code: 637, stateCode: 22, name: "NARAYANPUR" },
  { code: 386, stateCode: 22, name: "RAIGARH" },
  { code: 387, stateCode: 22, name: "RAIPUR" },
  { code: 388, stateCode: 22, name: "RAJNANDGAON" },
  { code: 762, stateCode: 22, name: "SAKTI" },
  { code: 763, stateCode: 22, name: "SARANGARH BILAIGARH" },
  { code: 642, stateCode: 22, name: "SUKMA" },
  { code: 648, stateCode: 22, name: "SURAJPUR" },
  { code: 389, stateCode: 22, name: "SURGUJA" },
  { code: 667, stateCode: 23, name: "AGAR MALWA" },
  { code: 639, stateCode: 23, name: "ALIRAJPUR" },
  { code: 390, stateCode: 23, name: "ANUPPUR" },
  { code: 391, stateCode: 23, name: "ASHOKNAGAR" },
  { code: 392, stateCode: 23, name: "BALAGHAT" },
  { code: 393, stateCode: 23, name: "BARWANI" },
  { code: 394, stateCode: 23, name: "BETUL" },
  { code: 395, stateCode: 23, name: "BHIND" },
  { code: 396, stateCode: 23, name: "BHOPAL" },
  { code: 397, stateCode: 23, name: "BURHANPUR" },
  { code: 398, stateCode: 23, name: "CHHATARPUR" },
  { code: 399, stateCode: 23, name: "CHHINDWARA" },
  { code: 400, stateCode: 23, name: "DAMOH" },
  { code: 401, stateCode: 23, name: "DATIA" },
  { code: 402, stateCode: 23, name: "DEWAS" },
  { code: 403, stateCode: 23, name: "DHAR" },
  { code: 404, stateCode: 23, name: "DINDORI" },
  { code: 405, stateCode: 23, name: "EAST NIMAR" },
  { code: 406, stateCode: 23, name: "GUNA" },
  { code: 407, stateCode: 23, name: "GWALIOR" },
  { code: 408, stateCode: 23, name: "HARDA" },
  { code: 410, stateCode: 23, name: "INDORE" },
  { code: 411, stateCode: 23, name: "JABALPUR" },
  { code: 412, stateCode: 23, name: "JHABUA" },
  { code: 413, stateCode: 23, name: "KATNI" },
  { code: 414, stateCode: 23, name: "KHARGONE" },
  { code: 415, stateCode: 23, name: "MANDLA" },
  { code: 416, stateCode: 23, name: "MANDSAUR" },
  { code: 417, stateCode: 23, name: "MORENA" },
  { code: 409, stateCode: 23, name: "NARMADAPURAM" },
  { code: 418, stateCode: 23, name: "NARSINGHPUR" },
  { code: 419, stateCode: 23, name: "NEEMUCH" },
  { code: 722, stateCode: 23, name: "Niwari" },
  { code: 420, stateCode: 23, name: "PANNA" },
  { code: 421, stateCode: 23, name: "RAISEN" },
  { code: 422, stateCode: 23, name: "RAJGARH" },
  { code: 423, stateCode: 23, name: "RATLAM" },
  { code: 424, stateCode: 23, name: "REWA" },
  { code: 425, stateCode: 23, name: "SAGAR" },
  { code: 426, stateCode: 23, name: "SATNA" },
  { code: 427, stateCode: 23, name: "SEHORE" },
  { code: 428, stateCode: 23, name: "SEONI" },
  { code: 429, stateCode: 23, name: "SHAHDOL" },
  { code: 430, stateCode: 23, name: "SHAJAPUR" },
  { code: 431, stateCode: 23, name: "SHEOPUR" },
  { code: 432, stateCode: 23, name: "SHIVPURI" },
  { code: 433, stateCode: 23, name: "SIDHI" },
  { code: 638, stateCode: 23, name: "SINGRAULI" },
  { code: 434, stateCode: 23, name: "TIKAMGARH" },
  { code: 435, stateCode: 23, name: "UJJAIN" },
  { code: 436, stateCode: 23, name: "UMARIA" },
  { code: 437, stateCode: 23, name: "VIDISHA" },
  { code: 438, stateCode: 24, name: "AHMADABAD" },
  { code: 439, stateCode: 24, name: "AMRELI" },
  { code: 440, stateCode: 24, name: "ANAND" },
  { code: 672, stateCode: 24, name: "ARVALLI" },
  { code: 441, stateCode: 24, name: "BANAS KANTHA" },
  { code: 442, stateCode: 24, name: "BHARUCH" },
  { code: 443, stateCode: 24, name: "BHAVNAGAR" },
  { code: 676, stateCode: 24, name: "BOTAD" },
  { code: 668, stateCode: 24, name: "CHHOTAUDEPUR" },
  { code: 444, stateCode: 24, name: "DANG" },
  { code: 674, stateCode: 24, name: "DEVBHUMI DWARKA" },
  { code: 445, stateCode: 24, name: "DOHAD" },
  { code: 446, stateCode: 24, name: "GANDHINAGAR" },
  { code: 675, stateCode: 24, name: "GIR SOMNATH" },
  { code: 447, stateCode: 24, name: "JAMNAGAR" },
  { code: 448, stateCode: 24, name: "JUNAGADH" },
  { code: 449, stateCode: 24, name: "KACHCHH" },
  { code: 450, stateCode: 24, name: "KHEDA" },
  { code: 451, stateCode: 24, name: "MAHESANA" },
  { code: 669, stateCode: 24, name: "Mahisagar" },
  { code: 673, stateCode: 24, name: "MORBI" },
  { code: 452, stateCode: 24, name: "NARMADA" },
  { code: 453, stateCode: 24, name: "NAVSARI" },
  { code: 454, stateCode: 24, name: "PANCH MAHALS" },
  { code: 455, stateCode: 24, name: "PATAN" },
  { code: 456, stateCode: 24, name: "PORBANDAR" },
  { code: 457, stateCode: 24, name: "RAJKOT" },
  { code: 458, stateCode: 24, name: "SABAR KANTHA" },
  { code: 459, stateCode: 24, name: "SURAT" },
  { code: 460, stateCode: 24, name: "SURENDRANAGAR" },
  { code: 641, stateCode: 24, name: "TAPI" },
  { code: 461, stateCode: 24, name: "VADODARA" },
  { code: 462, stateCode: 24, name: "VALSAD" },
  { code: 466, stateCode: 27, name: "AHMEDNAGAR" },
  { code: 467, stateCode: 27, name: "AKOLA" },
  { code: 468, stateCode: 27, name: "AMRAVATI" },
  { code: 469, stateCode: 27, name: "AURANGABAD" },
  { code: 470, stateCode: 27, name: "BEED" },
  { code: 471, stateCode: 27, name: "BHANDARA" },
  { code: 472, stateCode: 27, name: "BULDHANA" },
  { code: 473, stateCode: 27, name: "CHANDRAPUR" },
  { code: 474, stateCode: 27, name: "DHULE" },
  { code: 475, stateCode: 27, name: "GADCHIROLI" },
  { code: 476, stateCode: 27, name: "GONDIA" },
  { code: 477, stateCode: 27, name: "HINGOLI" },
  { code: 478, stateCode: 27, name: "JALGAON" },
  { code: 479, stateCode: 27, name: "JALNA" },
  { code: 480, stateCode: 27, name: "KOLHAPUR" },
  { code: 481, stateCode: 27, name: "LATUR" },
  { code: 482, stateCode: 27, name: "MUMBAI" },
  { code: 483, stateCode: 27, name: "MUMBAI SUBURBAN" },
  { code: 484, stateCode: 27, name: "NAGPUR" },
  { code: 485, stateCode: 27, name: "NANDED" },
  { code: 486, stateCode: 27, name: "NANDURBAR" },
  { code: 487, stateCode: 27, name: "NASHIK" },
  { code: 488, stateCode: 27, name: "OSMANABAD" },
  { code: 665, stateCode: 27, name: "PALGHAR" },
  { code: 489, stateCode: 27, name: "PARBHANI" },
  { code: 490, stateCode: 27, name: "PUNE" },
  { code: 491, stateCode: 27, name: "RAIGAD" },
  { code: 492, stateCode: 27, name: "RATNAGIRI" },
  { code: 493, stateCode: 27, name: "SANGLI" },
  { code: 494, stateCode: 27, name: "SATARA" },
  { code: 495, stateCode: 27, name: "SINDHUDURG" },
  { code: 496, stateCode: 27, name: "SOLAPUR" },
  { code: 497, stateCode: 27, name: "THANE" },
  { code: 498, stateCode: 27, name: "WARDHA" },
  { code: 499, stateCode: 27, name: "WASHIM" },
  { code: 500, stateCode: 27, name: "YAVATMAL" },
  { code: 745, stateCode: 28, name: "Alluri Sitharama Raju" },
  { code: 744, stateCode: 28, name: "Anakapalli" },
  { code: 502, stateCode: 28, name: "ANANTAPUR" },
  { code: 753, stateCode: 28, name: "Annamayya" },
  { code: 750, stateCode: 28, name: "Bapatla" },
  { code: 503, stateCode: 28, name: "CHITTOOR" },
  { code: 505, stateCode: 28, name: "EAST GODAVARI" },
  { code: 748, stateCode: 28, name: "Eluru" },
  { code: 506, stateCode: 28, name: "GUNTUR" },
  { code: 746, stateCode: 28, name: "Kakinada" },
  { code: 747, stateCode: 28, name: "Konaseema" },
  { code: 510, stateCode: 28, name: "KRISHNA" },
  { code: 511, stateCode: 28, name: "KURNOOL" },
  { code: 755, stateCode: 28, name: "Nandyal" },
  { code: 749, stateCode: 28, name: "NTR" },
  { code: 751, stateCode: 28, name: "Palnadu" },
  { code: 743, stateCode: 28, name: "Parvathipuram Manyam" },
  { code: 517, stateCode: 28, name: "PRAKASAM" },
  { code: 515, stateCode: 28, name: "SPSR NELLORE" },
  { code: 754, stateCode: 28, name: "Sri Sathya Sai" },
  { code: 519, stateCode: 28, name: "SRIKAKULAM" },
  { code: 752, stateCode: 28, name: "Tirupati" },
  { code: 520, stateCode: 28, name: "VISAKHAPATANAM" },
  { code: 521, stateCode: 28, name: "VIZIANAGARAM" },
  { code: 523, stateCode: 28, name: "WEST GODAVARI" },
  { code: 504, stateCode: 28, name: "Y.S.R." },
  { code: 524, stateCode: 29, name: "BAGALKOTE" },
  { code: 528, stateCode: 29, name: "BALLARI" },
  { code: 527, stateCode: 29, name: "BELAGAVI" },
  { code: 526, stateCode: 29, name: "BENGALURU RURAL" },
  { code: 525, stateCode: 29, name: "BENGALURU URBAN" },
  { code: 529, stateCode: 29, name: "BIDAR" },
  { code: 531, stateCode: 29, name: "CHAMARAJANAGARA" },
  { code: 630, stateCode: 29, name: "CHIKKABALLAPURA" },
  { code: 532, stateCode: 29, name: "CHIKKAMAGALURU" },
  { code: 533, stateCode: 29, name: "CHITRADURGA" },
  { code: 534, stateCode: 29, name: "DAKSHINA KANNADA" },
  { code: 535, stateCode: 29, name: "DAVANGERE" },
  { code: 536, stateCode: 29, name: "DHARWAD" },
  { code: 537, stateCode: 29, name: "GADAG" },
  { code: 539, stateCode: 29, name: "HASSAN" },
  { code: 540, stateCode: 29, name: "HAVERI" },
  { code: 538, stateCode: 29, name: "KALABURAGI" },
  { code: 541, stateCode: 29, name: "KODAGU" },
  { code: 542, stateCode: 29, name: "KOLAR" },
  { code: 543, stateCode: 29, name: "KOPPAL" },
  { code: 544, stateCode: 29, name: "MANDYA" },
  { code: 545, stateCode: 29, name: "MYSURU" },
  { code: 546, stateCode: 29, name: "RAICHUR" },
  { code: 631, stateCode: 29, name: "RAMANAGARA" },
  { code: 547, stateCode: 29, name: "SHIVAMOGGA" },
  { code: 548, stateCode: 29, name: "TUMAKURU" },
  { code: 549, stateCode: 29, name: "UDUPI" },
  { code: 550, stateCode: 29, name: "UTTARA KANNADA" },
  { code: 738, stateCode: 29, name: "VIJAYANAGAR" },
  { code: 530, stateCode: 29, name: "VIJAYAPURA" },
  { code: 635, stateCode: 29, name: "YADGIR" },
  { code: 551, stateCode: 30, name: "NORTH GOA" },
  { code: 552, stateCode: 30, name: "SOUTH GOA" },
  { code: 553, stateCode: 31, name: "LAKSHADWEEP DISTRICT" },
  { code: 554, stateCode: 32, name: "ALAPPUZHA" },
  { code: 555, stateCode: 32, name: "ERNAKULAM" },
  { code: 556, stateCode: 32, name: "IDUKKI" },
  { code: 557, stateCode: 32, name: "KANNUR" },
  { code: 558, stateCode: 32, name: "KASARAGOD" },
  { code: 559, stateCode: 32, name: "KOLLAM" },
  { code: 560, stateCode: 32, name: "KOTTAYAM" },
  { code: 561, stateCode: 32, name: "KOZHIKODE" },
  { code: 562, stateCode: 32, name: "MALAPPURAM" },
  { code: 563, stateCode: 32, name: "PALAKKAD" },
  { code: 564, stateCode: 32, name: "PATHANAMTHITTA" },
  { code: 565, stateCode: 32, name: "THIRUVANANTHAPURAM" },
  { code: 566, stateCode: 32, name: "THRISSUR" },
  { code: 567, stateCode: 32, name: "WAYANAD" },
  { code: 610, stateCode: 33, name: "Ariyalur" },
  { code: 730, stateCode: 33, name: "CHENGALPATTU" },
  { code: 568, stateCode: 33, name: "CHENNAI" },
  { code: 569, stateCode: 33, name: "COIMBATORE" },
  { code: 570, stateCode: 33, name: "CUDDALORE" },
  { code: 571, stateCode: 33, name: "DHARMAPURI" },
  { code: 572, stateCode: 33, name: "DINDIGUL" },
  { code: 573, stateCode: 33, name: "ERODE" },
  { code: 729, stateCode: 33, name: "KALLAKURICHI" },
  { code: 574, stateCode: 33, name: "KANCHIPURAM" },
  { code: 575, stateCode: 33, name: "KANNIYAKUMARI" },
  { code: 576, stateCode: 33, name: "KARUR" },
  { code: 577, stateCode: 33, name: "KRISHNAGIRI" },
  { code: 578, stateCode: 33, name: "MADURAI" },
  { code: 735, stateCode: 33, name: "Mayiladuthurai" },
  { code: 579, stateCode: 33, name: "NAGAPATTINAM" },
  { code: 580, stateCode: 33, name: "NAMAKKAL" },
  { code: 581, stateCode: 33, name: "PERAMBALUR" },
  { code: 582, stateCode: 33, name: "PUDUKKOTTAI" },
  { code: 583, stateCode: 33, name: "RAMANATHAPURAM" },
  { code: 731, stateCode: 33, name: "Ranipet" },
  { code: 584, stateCode: 33, name: "SALEM" },
  { code: 585, stateCode: 33, name: "SIVAGANGA" },
  { code: 733, stateCode: 33, name: "TENKASI" },
  { code: 586, stateCode: 33, name: "THANJAVUR" },
  { code: 587, stateCode: 33, name: "THE NILGIRIS" },
  { code: 588, stateCode: 33, name: "THENI" },
  { code: 589, stateCode: 33, name: "THIRUVALLUR" },
  { code: 590, stateCode: 33, name: "THIRUVARUR" },
  { code: 591, stateCode: 33, name: "TIRUCHIRAPPALLI" },
  { code: 592, stateCode: 33, name: "TIRUNELVELI" },
  { code: 732, stateCode: 33, name: "Tirupathur" },
  { code: 634, stateCode: 33, name: "TIRUPPUR" },
  { code: 593, stateCode: 33, name: "TIRUVANNAMALAI" },
  { code: 594, stateCode: 33, name: "TUTICORIN" },
  { code: 595, stateCode: 33, name: "VELLORE" },
  { code: 596, stateCode: 33, name: "VILLUPURAM" },
  { code: 597, stateCode: 33, name: "VIRUDHUNAGAR" },
  { code: 598, stateCode: 34, name: "KARAIKAL" },
  { code: 599, stateCode: 34, name: "MAHE" },
  { code: 600, stateCode: 34, name: "PONDICHERRY" },
  { code: 601, stateCode: 34, name: "YANAM" },
  { code: 603, stateCode: 35, name: "NICOBARS" },
  { code: 632, stateCode: 35, name: "NORTH AND MIDDLE ANDAMAN" },
  { code: 602, stateCode: 35, name: "SOUTH ANDAMANS" },
  { code: 501, stateCode: 36, name: "ADILABAD" },
  { code: 690, stateCode: 36, name: "BHADRADRI KOTHAGUDEM" },
  { code: 686, stateCode: 36, name: "HANUMAKONDA" },
  { code: 507, stateCode: 36, name: "HYDERABAD" },
  { code: 681, stateCode: 36, name: "Jagitial" },
  { code: 689, stateCode: 36, name: "JANGOAN" },
  { code: 687, stateCode: 36, name: "JAYASHANKAR BHUPALAPALLY" },
  { code: 695, stateCode: 36, name: "JOGULAMBA GADWAL" },
  { code: 685, stateCode: 36, name: "KAMAREDDY" },
  { code: 508, stateCode: 36, name: "KARIMNAGAR" },
  { code: 509, stateCode: 36, name: "KHAMMAM" },
  { code: 699, stateCode: 36, name: "KUMURAM BHEEM ASIFABAD" },
  { code: 688, stateCode: 36, name: "MAHABUBABAD" },
  { code: 512, stateCode: 36, name: "MAHABUBNAGAR" },
  { code: 684, stateCode: 36, name: "MANCHERIAL" },
  { code: 513, stateCode: 36, name: "MEDAK" },
  { code: 700, stateCode: 36, name: "MEDCHAL MALKAJGIRI" },
  { code: 720, stateCode: 36, name: "Mulugu" },
  { code: 694, stateCode: 36, name: "NAGARKURNOOL" },
  { code: 514, stateCode: 36, name: "NALGONDA" },
  { code: 721, stateCode: 36, name: "Narayanpet" },
  { code: 680, stateCode: 36, name: "Nirmal" },
  { code: 516, stateCode: 36, name: "NIZAMABAD" },
  { code: 682, stateCode: 36, name: "PEDDAPALLI" },
  { code: 683, stateCode: 36, name: "RAJANNA SIRCILLA" },
  { code: 518, stateCode: 36, name: "RANGA REDDY" },
  { code: 691, stateCode: 36, name: "SANGAREDDY" },
  { code: 692, stateCode: 36, name: "SIDDIPET" },
  { code: 696, stateCode: 36, name: "SURYAPET" },
  { code: 698, stateCode: 36, name: "VIKARABAD" },
  { code: 693, stateCode: 36, name: "WANAPARTHY" },
  { code: 522, stateCode: 36, name: "WARANGAL" },
  { code: 697, stateCode: 36, name: "YADADRI BHUVANAGIRI" },
  { code: 6, stateCode: 37, name: "KARGIL" },
  { code: 9, stateCode: 37, name: "LEH LADAKH" },
  { code: 465, stateCode: 38, name: "DADRA AND NAGAR HAVELI" },
  { code: 463, stateCode: 38, name: "DAMAN" },
  { code: 464, stateCode: 38, name: "DIU" },
];

export function districtsOfState(stateCode: number | null | undefined): LgdDistrict[] {
  if (!stateCode) return [];
  return LGD_DISTRICTS.filter((d) => d.stateCode === stateCode);
}

export function stateByName(name: string): LgdState | undefined {
  const needle = name.trim().toUpperCase();
  return LGD_STATES.find((s) => s.name === needle);
}
